### ISSUE TITLE
"General" tab --> EMSA Score display (water drop)

### ISSUE THREAD

**Issue by david-ITCL** [EnergyWater/EMSA#1]
Change the Score visual display from this:
![image](https://user-images.githubusercontent.com/33861863/33163310-381c8174-d02e-11e7-9de5-0dd3273f0aad.png)
To this:
![image](https://user-images.githubusercontent.com/33861863/33162625-cbccf6be-d02a-11e7-9adb-597b542e33a2.png)

**Comment by WINGSTeam** [comment]
We used the bar (instead of water drop) because it was not supported by all browsers according to the comments received by partners. -WINGS

**Comment by david-ITCL** [comment]
We would like to propose an intermediate solution to be able to maintain the water drop. 
We propose to get rid of the water-animated part and insert 4 or 5 fixed pictures of a water drop with different filling levels according to their EMSA Score, just like we do now with the 5-stars score.

**Comment by WINGSTeam** [comment]
> We would like to propose an intermediate solution to be able to maintain the water drop.
> We propose to get rid of the water-animated part and insert 4 or 5 fixed pictures of a water drop with different filling levels according to their EMSA Score, just like we do now with the 5-stars score.

We have introduce your proposed solution with the 5 fixed pictures of the water drop.

**Comment by david-ITCL** [comment]
@WINGSTeam thanks, we proceed to close this issue
