### ISSUE TITLE
Calculation problems

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#10]
This issue regards all the calculation problems that the partners consider necessary to solve in this module.

Please, comment the new feedback indicating the origin of the issue in orden from the scenarios module screen to the particular issue starting with "Feedback:", to difference this comments from others, for example, Efficiency Questions - Equipment Pump - E01F24 and then the issue

**Comment by WINGSTeam** [comment]
Please reopen when an issue regarding calculations appears!
