### ISSUE TITLE
Additionnal comments regarding Boilers and Saving simulator

### ISSUE THREAD

**Issue by cbarbaux** [EnergyWater/EMSA#101]
Hi everyone,

Please find in the attached documents some additional comments regarding mainly the boiler data evaluation tab and some typos in the saving simulator.

Additionally, we've tried to understand why some charts appear with values at 0, etc. (see previous issue thread if needed) and one reason could be that modification in the data evaluation tab are only taken into consideration when the submit button of the process/equipment page is used. All other options (save button, submit button on the summary table) don't seem to have any effect.
There might be another issue though, because there are still some equipment for which we don't get values in chart (cooling tower for instance)
[20180528 EMSA pro comments GF.xlsx](https://github.com/EnergyWater/EMSA/files/2044697/20180528.EMSA.pro.comments.GF.xlsx)

**Comment by WINGSTeam** [comment]
We attach here our response to your comments. 
[20180528.EMSA.pro.comments.GF.xlsx](https://github.com/EnergyWater/EMSA/files/2053162/20180528.EMSA.pro.comments.GF.xlsx)



> There might be another issue though, because there are still some equipment for which we don't get values in chart (cooling tower for instance)



> There might be another issue though, because there are still some equipment for which we don't get values in chart (cooling tower for instance)

We cannot replicate this issue. As you can see in the image below cooling towers have values in the charts. Please, make sure you complete all the questions in the data evaluation module (efficiency questions), so all the necessary values are calculated, and also make sure you submitted your scenario. If you continue to have the same problem, please send us your account credentials in order to check it as well. 
![capture17](https://user-images.githubusercontent.com/33901428/40709926-063023da-6400-11e8-9149-06955c93dade.PNG)

**Comment by cbarbaux** [comment]
@WINGSTeam 
Thanks for fixing the typos.

There's still something we want to make sure regarding the save and submit buttons.

We've entered data for evey process and equipment and submit the whole scenario. We had some bugs regarding the content of the graphs (empty graphs) but we'll try to replicate this later this week to understand better what could have happened.
Nevertheless, one thing is sure because we already replicated it: if someone modifies the answers to the efficiency questions after submitting the scenario and use the save button, **the values in the results graphs are put to 0**. Meaning the previous results are erased and the new results are not displayed.
We also tried submitting again the whole scenario after modifying answers on different process and equipment but it had no effect. We tried both using the submit button on the summary table page of the efficiency questions and using the submit scenario button --> see pictures below)
![submit](https://user-images.githubusercontent.com/34023517/40912269-5e5691a8-67f1-11e8-96ee-0f77fb19f5d5.png)
![submitscenario](https://user-images.githubusercontent.com/34023517/40912272-61c1d2e4-67f1-11e8-8430-b29650c2a543.png)

 
We could only update values in graphs submitting the modification on each process and equipment page.
![submitprocess](https://user-images.githubusercontent.com/34023517/40912363-9da58b20-67f1-11e8-8a59-cfb4f92023fa.png)

This is a real problem for us, which explains some of the problems we had previously with valueless graphs. We can also expect users outside of the consortium to encounter the same problems.
A save button is ok as long as it doesn't erase previous results. If it does, then we think it has to be removed (to only leave the submit button) or there has to be a message saying that new values won't be taken into consideration unless scenario is submitted again.
Also the different submit buttons should have the same effect (or have a different name if they have different effects). Meaning the submission of modification should be available from the three submit buttons.

**Comment by WINGSTeam** [comment]
> A save button is ok as long as it doesn't erase previous results. If it does, then we think it has to be removed (to only leave the submit button) or there has to be a message saying that new values won't be taken into consideration unless scenario is submitted again.

We removed the save button from all processes and equipment.



> Also the different submit buttons should have the same effect (or have a different name if they have different effects). Meaning the submission of modification should be available from the three submit buttons.

The submit buttons are all necessary. The first one (first image below) submits the values for a particular process or equipment. The second one (second image below) submits the table with all the processes and equipment the user chose in a scenario. And the third one (third image below) submits the whole scenario, that is the general questions, the efficiency questions and the management questions.


![](https://user-images.githubusercontent.com/34023517/40912269-5e5691a8-67f1-11e8-96ee-0f77fb19f5d5.png)


![](https://user-images.githubusercontent.com/34023517/40912363-9da58b20-67f1-11e8-8a59-cfb4f92023fa.png)

![](https://user-images.githubusercontent.com/34023517/40912272-61c1d2e4-67f1-11e8-8430-b29650c2a543.png)
