### ISSUE TITLE
Process-Equipment follow-up - SOCAMEX

### ISSUE THREAD

**Issue by WINGSTeam** [EnergyWater/EMSA#102]
We attach here the revised excel SOCAMEX provided us with. We were not be able to replicate the problems you mentioned about the simulator. So, please, give us your account credentials in order to check the problems from your account. And also, could tell us what browser did you use for the evaluation process, so we can check the problems about the benchmarking module you are referring to? 
[Process-Equipment follow-up 25-MaySOCAMEX.xlsx](https://github.com/EnergyWater/EMSA/files/2047587/Process-Equipment.follow-up.25-MaySOCAMEX.xlsx)

**Comment by Yolanda-Ballesteros** [comment]
Thank you @WINGSTeam . I'm sending the credentials by email to you.
