### ISSUE TITLE
SOCAMEX'S last round of validations

### ISSUE THREAD

**Issue by Yolanda-Ballesteros** [EnergyWater/EMSA#103]
With regard to the implemented values of the predicted savings and min-max investment (euros), we have checked whether implemented percentages are in line with those specified in the Excel sheets.
[Process-Equipment follow-up 01JunSOCAMEX.xlsx](https://github.com/EnergyWater/EMSA/files/2062671/Process-Equipment.follow-up.01JunSOCAMEX.xlsx)

**Comment by WINGSTeam** [comment]
You can find our comments and some questions attached here.
[Process-Equipment.follow-up.01JunSOCAMEX (1).xlsx](https://github.com/EnergyWater/EMSA/files/2071406/Process-Equipment.follow-up.01JunSOCAMEX.1.xlsx)

**Comment by Yolanda-Ballesteros** [comment]
@WINGSTeam  Sorry for the delay in replying. We have been abroad for a meeting. Here I attach an example (screenshot) of the problems detected in the processes Flotation, Aerobic Biological Treatment, Anaerobic Biological Treatment, Dissolved Air Supplier and Equipment Polyelectrolyte Preparation. You can see that in the "Savings (%)" column, the percentage appears correctly (5 in this case, for those improvements which are able to produce savings, which are the two first ones). The investment Min and Max also appear. But the other columns are empty in this case (in the case of the attached screenshot), I mean, full with zeros. Nevertheless, if we repeat the simulation with the same selection of improvements, some times the columns "Current energy consumption", "energy saving", "new energy consumption" and "CO2 emission saving) also appear filled in with numbers other than zero. I mean, sometimes the EMSA seems to calculate the current energy consumption, the energy saving, the new energy consumption and the CO2 saving, but other times only the predicted saving percentage (5  in this case) is displayed. We don't know whether this is only happening to us, or any other partner has experienced it. Regarding to the issue addressed in rows 67 to 72 of the excel attached in the first comment of this issue (number 103), WINGS proposes to discuss it with all the partners together. I made that observation because I was not here when the project started, but maybe you did discuss it in the past, and you considered (owing to, for sure, good reasons) that the EMSA performed the calculations this way. It is not my intention to re-evaluate now the things that have been discussed before, so if this is what the project arranged in the beginning, then it is OK now. Thank you!

![image](https://user-images.githubusercontent.com/39729301/41232450-ae7049aa-6d86-11e8-9416-1b00247eeb6e.png)

**Comment by WINGSTeam** [comment]
> But the other columns are empty in this case (in the case of the attached screenshot), I mean, full with zeros.

The values are probably zero because you did not complete the energy consumption question in the data evaluation module.  Answer this question and resubmit your scenario and the values will be calculated. If you continue to have this problem please come back to us in order to check it again.

**Comment by Yolanda-Ballesteros** [comment]
Yes, it could be that I was performing the simulation in a scenario where the energy consumption was lack! I have repeated it many other times ensuring that such value was present, and I have found no problem!! It was quite obvious, sorry for not having noted that. Thanks!
