### ISSUE TITLE
Additional comments on EMSA lite

### ISSUE THREAD

**Issue by cbarbaux** [EnergyWater/EMSA#104]
Hi,
As we are uploading data from our past audits into the EMSA Lite we have identified several small bugs.

- In the information tab, when selecting France as a country, the list of states show two small errors:
"Guadeloupe" is ill-written (missing the o)
the "Hauts-de-France" state is separated into two states "Hauts" and "de France"

- the company sector list is in a weird order with the other industries being randomly distributed in the list (paper industry at the begining, chemical industry in the middle, rest of the other industry at the bottom of the list)
![image](https://user-images.githubusercontent.com/34023517/42103720-2b00e582-7bca-11e8-8e83-039f3ca29562.png)

- The visualisation of the different steps of the assessment change during the assessment.
On the first 2 steps, the visualisation show 8 steps
![image](https://user-images.githubusercontent.com/34023517/42103167-8f0351f2-7bc8-11e8-8e35-85092d8a1d8c.png)
On the following steps, there are only 6 steps in the process, the 2 first ones disappear
![image](https://user-images.githubusercontent.com/34023517/42103194-a2a53590-7bc8-11e8-83db-f059cc7532cd.png)

-  the "Back" button on the company sector selection page, goes back to the General questions / Efficiency questions / Management Questions table instead of going back to the previous step.

- On the first page of the General questions, the list of Fuel Consumption is a random order. the list in neither alphabetical nor logical (natural gas first in that cas, fuel oil n°1 and n°2 just before other)
A similar comment can be made to all lists in the tool: company sector, process, equipment: there doesn't seem to be any specific order for items. An alphabetical ranking of items in the list could help navigating.

**Comment by WINGSTeam** [comment]
> In the information tab, when selecting France as a country, the list of states show two small errors:
> "Guadeloupe" is ill-written (missing the o)
> the "Hauts-de-France" state is separated into two states "Hauts" and "de France"

Errors fixed.



> the company sector list is in a weird order with the other industries being randomly distributed in the list (paper industry at the begining, chemical industry in the middle, rest of the other industry at the bottom of the list)

Sectors are in alphabetical order now.



> The visualisation of the different steps of the assessment change during the assessment.
> On the first 2 steps, the visualisation show 8 steps

Fixed.



> the "Back" button on the company sector selection page, goes back to the General questions / Efficiency questions / Management Questions table instead of going back to the previous step.

Back button fixed.



> On the first page of the General questions, the list of Fuel Consumption is a random order. the list in neither alphabetical nor logical (natural gas first in that cas, fuel oil n°1 and n°2 just before other)
> A similar comment can be made to all lists in the tool: company sector, process, equipment: there doesn't seem to be any specific order for items. An alphabetical ranking of items in the list could help navigating.

The list of fuels, the lists of sectors are in alphabetical order. Processes and equipment  lists and tables are in alphabetical order as well.
