### ISSUE TITLE
Process and equipment ratio

### ISSUE THREAD

**Issue by cbarbaux** [EnergyWater/EMSA#105]
On the results tab, for the EMSA Pro, the table showing the calculed ratio for equipment and process have its first cell updated only when clicking on process and not on equipment.
Consequently, the table keeps in memory the name of the last process selected even though it shows value of an equipment.

See picture below: the value and name of column are well adapted to the boiler equipment that was selected, but the first cell still shows the name of the previously selected process (decantation).

The problem can be found both on the general tab and the efficiency tab of the results.

![image](https://user-images.githubusercontent.com/34023517/42946304-d716ef1a-8b6a-11e8-9334-ff0ba616134c.png)

**Comment by WINGSTeam** [comment]
Bug is fixed.
