### ISSUE TITLE
EA contact

### ISSUE THREAD

**Issue by cbarbaux** [EnergyWater/EMSA#106]
Using the EMSA Lite, I have the following error message when clicking on the EMSA support module
![image](https://user-images.githubusercontent.com/34023517/42950858-2d9abca4-8b75-11e8-8630-58abb72ee98b.png)
Meaning I'm asked to be connected with an EA to be able to reach EA.

Using the EMSA Pro, in the Improvement Action module when trying to connect to another EA, there is no research bar like in the EMSA support, which makes it hard to sort and select an adequate EA.
![image](https://user-images.githubusercontent.com/34023517/42951097-b67b58da-8b75-11e8-962e-f94961e303d3.png)

**Comment by WINGSTeam** [comment]
We changed the previous warning to the following one.
![capture10](https://user-images.githubusercontent.com/33901428/43002305-f1e96266-8c30-11e8-93bc-176e28b9b565.PNG)

Also, we added a search-box for selecting an angel, in the  Improvement Action module.

**Comment by cbarbaux** [comment]
Thanks for the modification.
The first comment regarding the warning meant to say that the whole warning has to be desactivated, so that companies can actually use the EMSA support module to connect with EA while using EMSA lite
