### ISSUE TITLE
EMSA General issues

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#108]
Currently, we are checking the EMSA's improvements management and assigned improvements module, and we have realised of some issues.
- When a company adds improvenets to the implementation plan, the Energy Angel  is not notified
- When a Company removes it's Energy Angel  or rejects any one, the Energy Angel is not notified.
- If an Energy Angel rejects a company's request, the company is not  notified.
- In the Energy Angel rating screen, the number format in Firefox browser has some size problems as you could check in the picture. 

![image](https://user-images.githubusercontent.com/33861863/43320714-ac4aea76-91a9-11e8-8b53-763576da8282.png)

**Comment by WINGSTeam** [comment]
> When a company adds improvenets to the implementation plan, the Energy Angel is not notified
> When a Company removes it's Energy Angel or rejects any one, the Energy Angel is not notified.
> If an Energy Angel rejects a company's request, the company is not notified

Could you please be more specific about notifications? Do you mean an email notification? An alert?



> In the Energy Angel rating screen, the number format in Firefox browser has some size problems as you could check in the picture.

This problem is fixed.

**Comment by AaronITCL** [comment]
> When a company adds an improvement to the implementation plan, the Energy Angel is not notified
> When a Company removes it's Energy Angel or rejects any one, the Energy Angel is not notified.
> If an Energy Angel rejects a company's request, the company is not notified

> Could you please be more specific about notifications? Do you mean an email notification? An alert?

For now, EMSA should send at least an alert as a notificaction.

**Comment by WINGSTeam** [comment]
> For now, EMSA should send at least an alert as a notificaction.

Alerts have been added.
