### ISSUE TITLE
Heat Exchange Process issue

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#109]
On the P03F21 Question "Is the water consumption estimated, measured or does it correspond to the entire water flow?", EMSA displays only 2 of the 3 possible answer that should display, we miss the option "It corresponds to the entire water flow".

As it is wrongly in the EMSA:
![image](https://user-images.githubusercontent.com/33861863/46010268-52caa200-c0c2-11e8-9794-b0f0c1efc129.png)

As it is correctly in the Excel:
![image](https://user-images.githubusercontent.com/33861863/46010424-ddab9c80-c0c2-11e8-9754-5584ec4d526a.png)

**Comment by WINGSTeam** [comment]
Fixed
