### ISSUE TITLE
Unit problems

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#11]
This issue regards all the unit problems that the partners consider necessary to solve in this module.

Please, comment the new feedback indicating the origin of the issue in orden from the scenarios module screen to the particular issue starting with "Feedback:", to difference this comments from others, for example, Efficiency Questions - Equipment Pump - E01F24 and then the issue

**Comment by AaronITCL** [comment]
Feedback:
Efficiency Questions - Eqipment Blower - E26F14 ->  Working hours redundant units.
It is not necessary to set a unit selector, the question itself indicates the units.

![image](https://user-images.githubusercontent.com/33861863/33319396-d2f7a58e-d43e-11e7-81d0-59623f304464.png)

**Comment by AaronITCL** [comment]
Feedback:
Efficiency Questions - Eqipment Ion Exchanger - E05F10 -> Ion Exchange unit problem.
Change the question to “What is the conductivity of the water? (µS/cm) “

![image](https://user-images.githubusercontent.com/33861863/33319467-22a17e52-d43f-11e7-969f-b895a7722723.png)

**Comment by AaronITCL** [comment]
Feedback:
Efficiency Questions - Eqipment Decanter - E18F18 -> Decanter water flow unit problem.
EMSA doesn´t show the common volume units for this type of water related questions. It is necessary to add that units.

![image](https://user-images.githubusercontent.com/33861863/33319576-894d34fc-d43f-11e7-93ea-2c34ac873983.png)

![image](https://user-images.githubusercontent.com/33861863/33319580-8c0c2a2c-d43f-11e7-8a24-e89ff2b67c56.png)

**Comment by WINGSTeam** [comment]
> Feedback:
> Efficiency Questions - Eqipment Blower - E26F14 -> Working hours redundant units.
> It is not necessary to set a unit selector, the question itself indicates the units.

Done

**Comment by WINGSTeam** [comment]
> Feedback:
> Efficiency Questions - Eqipment Decanter - E18F18 -> Decanter water flow unit problem.
> EMSA doesn´t show the common volume units for this type of water related questions. It is necessary to add that units.

Done

**Comment by WINGSTeam** [comment]
> Feedback:
> Efficiency Questions - Eqipment Ion Exchanger - E05F10 -> Ion Exchange unit problem.
> Change the question to “What is the conductivity of the water? (µS/cm) “

Done
