### ISSUE TITLE
Pump equipment issue

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#110]
EMSA is displaying wrongly some recomendations and improvements of some questions in the pump equipment.
The incorrect questions are those shown in the picture, you can check as well the recommended value and the improvement and recommendation which should display the EMSA if the value is not met.

![image](https://user-images.githubusercontent.com/33861863/46951837-68ac0100-d089-11e8-9674-cfd79d837053.png)

**Comment by WINGSTeam** [comment]
We cannot replicate this problem. For us the improvements are displayed according the recommended values from the excel file. Could you please be more specific? Could you describe your testing process, what values did you input in which questions? And also you may add some screenshots from the results in order to locate the problem.

**Comment by AaronITCL** [comment]
The values inserted in EMSA are the following ones.
![image](https://user-images.githubusercontent.com/33861863/47007368-5937c100-d138-11e8-9240-650db1061bd0.png)
![image](https://user-images.githubusercontent.com/33861863/47007373-5b018480-d138-11e8-97e6-fce27c10e86f.png)
Those are the ones needed to calculate the recommended value. In this example, I choose a boiler.
Boiler pressure: 10m
Pump pressure: 15m
The recommended value indicates:
1,1*Boiler pressure < Pump pressure < 1,2*Boiler pressire
This means that the following relation is incorrect:
1,1* 10m < 15m < 1,2*10m    <-      11m < 15m < 12m
So the recommended value is not met and EMSA should display the direct improvement actions.
![image](https://user-images.githubusercontent.com/33861863/47011980-79b94880-d143-11e8-9e82-fbd3bfa2afaa.png)
But the improvement: "Check pump pressure at working conditions, pump efficiency could be improved, Consider selecting a working pressure around 15% over heater pressure" doesn't appear.

**Comment by WINGSTeam** [comment]
I run the exact same test from 2 of our test accounts and the improvement appears. Could you describe step by step the process you follow (scenario, process,equipment), so I can check it  from the ICLT account?

**Comment by AaronITCL** [comment]
Of course, by the way I have resubmited that scenario before check and report this issue.
I will send you the ITCL account credentials by email.

**Comment by WINGSTeam** [comment]
Well we manage to located the problem. It wasn't the particular improvements they did not appear, it was a more general problem about listing the improvements for equipment. It is fixed now. You can test it as well.
