### ISSUE TITLE
P27 Aerobic Biological Treatment 2018 Revised_SM

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#111]
Attached you can find P27 priority process revision.
We made both technical and grammatical revision, changing the wording of several questions and explanations, and adding some more efficiency reccomendations.
[P27 Aerobic Biological Treatment 2018 Revised_SM.xlsx](https://github.com/EnergyWater/EMSA/files/2479090/P27.Aerobic.Biological.Treatment.2018.Revised_SM.xlsx)

**Comment by WINGSTeam** [comment]
In the revised excels we need from you to highlight the particular columns that we need to change because our timeline is very tight. Could you please resend us the revised document after you mark the changes that you made?

**Comment by Matilde-SmartFuture** [comment]
Attached you can find the document: contents changed are written in red.

[P27 Aerobic Biological Treatment 2018 Revised_SM_1.xlsx](https://github.com/EnergyWater/EMSA/files/2486649/P27.Aerobic.Biological.Treatment.2018.Revised_SM_1.xlsx)

**Comment by WINGSTeam** [comment]
The updates you proposed are implemented on the tool.
