### ISSUE TITLE
E37

### ISSUE THREAD

**Issue by Yolanda-Ballesteros** [EnergyWater/EMSA#112]
In cell P09E37F04 of Sheet E37, "motors" should have been written with just one "s". It has been highlighted in red in the corresponding Excel file.

**Comment by WINGSTeam** [comment]
These change is are already implemented on the tool from the first round of review of the excels.  Also, you mention an excel file but there is not one attached here. Did you forgot to upload it or could we find it somewhere else?

**Comment by WINGSTeam** [comment]
The changes that you are already referring to are applied to the tool from the first round of the review of Excel files.
