### ISSUE TITLE
E23

### ISSUE THREAD

**Issue by Yolanda-Ballesteros** [EnergyWater/EMSA#113]
Two recommendations are missing in E23 sheet:
- In question P13E23F05, the question "Do you know your energy consumption?", recommended value is "yes", but then an improvement action should be given, for example: "Install measurement equipment in the company to measure energy consumption".
- In question P13E23F10, the same for the water flow.

**Comment by WINGSTeam** [comment]
These changes you referring to, are already implemented on the tool from the first round of reviewing the excels.
