### ISSUE TITLE
E26 SM revision

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#114]
Attached you can find E26 priority equipment revision.
We made both technical and grammatical revision: the contents changed are hilighted in red.

[E26 Blower 2018 Revised_SM.xlsx](https://github.com/EnergyWater/EMSA/files/2535484/E26.Blower.2018.Revised_SM.xlsx)

**Comment by WINGSTeam** [comment]
Done.
