### ISSUE TITLE
E28 SM revision

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#115]
Attached you can find E28 priority equipment revision.
We made both technical and grammatical revision: the contents changed are hilighted in red.

[E28 Decanter 2018_Revised_SM.xlsx](https://github.com/EnergyWater/EMSA/files/2535490/E28.Decanter.2018_Revised_SM.xlsx)

**Comment by WINGSTeam** [comment]
Done.
