### ISSUE TITLE
E07 SM Revision

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#116]
Attached you can find E07 priority equipment revision.
We made both technical and grammatical revision: the changed contents are highlighted in red.

In the original excel, many feature code references had been wrongly reported in the "value" and "equation" columns. It is then expected that, once references will be changed, calculation results will change.

[E07 Heat Exchanger 2018_Revised_SM.xlsx](https://github.com/EnergyWater/EMSA/files/2548839/E07.Heat.Exchanger.2018_Revised_SM.xlsx)

**Comment by WINGSTeam** [comment]
Done.
