### ISSUE TITLE
E06 SM Revision

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#117]
Attached you can find E06 priority equipment revision.
We added some further reccomendation or suggested action. We made both technical and grammatical revision: the changed contents are highlighted in red.

[E06 Heater 2018_Revised_SM.xlsx](https://github.com/EnergyWater/EMSA/files/2553083/E06.Heater.2018_Revised_SM.xlsx)

**Comment by WINGSTeam** [comment]
The changes you proposed are implemented on the tool.
