### ISSUE TITLE
Functionality and Display problems

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#12]
This issue regards all the functionality and displaying problems that the partners consider necessary to solve in this module.

Please, comment the new feedback indicating the origin of the issue in orden from the scenarios module screen to the particular issue starting with "Feedback:", to difference this comments from others, for example, Efficiency Questions - Equipment Pump - E01F24 and then the issue

**Comment by AaronITCL** [comment]
Feedback: Efficiency Questions - Edit table 
It is necessary to be capable to write more characters at the Main process name and Process name creation.

- Main Process:
![image](https://user-images.githubusercontent.com/33861863/33316221-7ff149d6-d433-11e7-81c4-4e74b9eae465.png)

- Process:
![image](https://user-images.githubusercontent.com/33861863/33316337-e6df7636-d433-11e7-8b24-a1367c746abf.png)

**Comment by AaronITCL** [comment]
In this comment, i will summary all the feedback received related to this module and this issue.
Also, i will indicate which ones are proposals. 
Finally, take into account that all of them are non-priority, the ones considered important will appear in another issue.
## GreenFlex
1. Efficiency Questions, Proposal: Some questions seem redundant when focusing on equipment : for instance regarding pumping we have in the list:
- Useof pumping (sludge, high pressure, condensate, feed water, drinking water)
- Type of fluid (water, sludge, etc.)
- Is the fluid corrosive
- Is the fluid viscous

The last two questions have to be automatically filled if the company select water/wastewater/sludge and can appear if they select another type of fluid

2. Efficiency Questions: There are some problems with question about thermal storage : 2nd question is about oil level instead of liquid level. The question about max pressure has a Y/N answer

3. Efficiency Questions, Proposal: I think it would also help if we could identify the equipment pages that have been filled.

4. General Questions, Proposal: Better if you hide the field to fill the annual consumption until the box has been selected.

5. Efficiency Questions, Proposal: We should let the possibility to companies to enter other processes and equipment that the one we identified, and let them register their power, running hours, energy consumption etc. For instance one of our pilot companies has an Reversible Electrodialisis to treat its feedwater. And I can’t insert it in the tool.

6. Management Questions: We have to hide the score given to each answer. We could even change the order of the possible answers to avoid always having the best one at the end of the list It will make sure that they read and select what is most representative of their situation and not go directly for the best.

**Comment by AaronITCL** [comment]
Feedback: 
Efficiency Questions - Equipment Pump- E01F51, E01F52 ,E01F53 and E01F54 related to E01F47-> PUMP display problems

Checking the conditions of that questions in the socamex excel:


Feature   code | Feature name | Condition
-- | -- | --
P01E01F51 | Steam pressure is enough to drive condensate to   boiler room? | **Ask   Only if Use = "Condensate pumping (boiler)"**
P01E01F52 | Control by heater water level ? | **Ask   Only if Use = "Heater water feeding"**
P01E01F53 | Nominal   heater/boiler pressure | **Ask   Only if Use = "Heater water feeding" or "Fire-tube boiler   water feeding"**
P01E01F54 | Nominal   stream production | **Ask   Only if Use = "Fire-tube Boiler    water feeding"**

Those cell are referenced to the following one:

![image](https://user-images.githubusercontent.com/33861863/33320126-74ae99bc-d441-11e7-9e6f-93d5f92794d2.png)

Currently the EMSA is displaying it wrongly.

**Comment by AaronITCL** [comment]
Feedback:
Efficiency Questions - Equipment Storage- E08F05 -> Storage, question problem.

![image](https://user-images.githubusercontent.com/33861863/33320380-55436408-d442-11e7-962e-b38ede1264f7.png)

Change the question from “What is max pressure specification of the equipment?” to “Is the pressure of the equipment less than its maximum permissible value?”

**Comment by WINGSTeam** [comment]
> Feedback: Efficiency Questions - Edit table
> It is necessary to be capable to write more characters at the Main process name and Process name creation.

How many characters should be? **This questions is addressed to all the partners for discussion.** Just keep in mind that if there are unlimited or a high value maybe the overall table at the end of the efficiency steps will became too large.

**Comment by WINGSTeam** [comment]
> Feedback:
> Efficiency Questions - Equipment Storage- E08F05 -> Storage, question problem.
> 
> 
> 
> Change the question from “What is max pressure specification of the equipment?” to “Is the pressure of the equipment less than its maximum permissible value?”

Done

**Comment by WINGSTeam** [comment]
> Feedback:
> Efficiency Questions - Equipment Pump- E01F51, E01F52 ,E01F53 and E01F54 related to E01F47-> PUMP display problems
> 
> Checking the conditions of that questions in the socamex excel:
> 
> Feature code	Feature name	Condition
> P01E01F51	Steam pressure is enough to drive condensate to boiler room?	Ask Only if Use = "Condensate pumping (boiler)"
> P01E01F52	Control by heater water level ?	Ask Only if Use = "Heater water feeding"
> P01E01F53	Nominal heater/boiler pressure	Ask Only if Use = "Heater water feeding" or "Fire-tube boiler water feeding"
> P01E01F54	Nominal stream production	Ask Only if Use = "Fire-tube Boiler  water feeding"
> Those cell are referenced to the following one:
> 
> 
> 
> Currently the EMSA is displaying it wrongly.

Done

**Comment by WINGSTeam** [comment]
> GreenFlex
> 
> Efficiency Questions, Proposal: Some questions seem redundant when focusing on equipment : for instance regarding pumping we have in the list:
> Useof pumping (sludge, high pressure, condensate, feed water, drinking water)
> Type of fluid (water, sludge, etc.)
> Is the fluid corrosive
> Is the fluid viscous
> The last two questions have to be automatically filled if the company select water/wastewater/sludge and can appear if they select another type of fluid

This is based on the specification. Should be discussed among the partners involved if a change is needed.

> 
> Efficiency Questions: There are some problems with question about thermal storage : 2nd question is about oil level instead of liquid level. The question about max pressure has a Y/N answer
> 
Could you please clarify for which equipment are you talking about?

**Comment by AaronITCL** [comment]
> Efficiency Questions: There are some problems with question about thermal storage : 2nd question is about oil level instead of liquid level. The question about max pressure has a Y/N answer

It is referred to the Storage Equipment, just change oil level by liquid level
![image](https://user-images.githubusercontent.com/33861863/33418448-29496ee6-d5a6-11e7-8b4b-c9b51971bae1.png)

Please, in order to accomplish with the deadline stablished for this friday, focus firstly in the prioritary questions of the simulator module until complete them, then proceed with non prioritory and proposal tasks.

**Comment by WINGSTeam** [comment]
> It is referred to the Storage Equipment, just change oil level by liquid level

Done

**Comment by WINGSTeam** [comment]
> Feedback: Efficiency Questions - Edit table
> It is necessary to be capable to write more characters at the Main process name and Process name creation.

We have increase the limit from 15 to 40 characters
