### ISSUE TITLE
Production ratios

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#13]
When a “production” ratio is calculated (i.e. € electricity /production unit  or  kWh Electricity / production unit), the production value has not to be converted, so if the user set for instance in the production cell (in general questions) 10000 tons of product and in the electricity cost 8000 €, the calculation of the ratio must be:
![image](https://user-images.githubusercontent.com/33861863/33318755-16b4405a-d43c-11e7-951c-140e56ae62ab.png)

And not as it is currently doing:
![image](https://user-images.githubusercontent.com/33861863/33318764-23586584-d43c-11e7-9f9a-a768efa333b3.png)

**Comment by WINGSTeam** [comment]
> When a “production” ratio is calculated (i.e. € electricity /production unit or kWh Electricity / production unit), the production value has not to be converted, so if the user set for instance in the production cell (in general questions) 10000 tons of product and in the electricity cost 8000 €, the calculation of the ratio must be:
> 
> 
> And not as it is currently doing:

From the specification we have implement the conversion of the values to the "basic" units .  So if you choose "gal" will be converted to m^3 and "Tons" to "kg",  for example: 1 Ton = 1000Kg, etc...
Should we change this conversion ?

**Comment by AaronITCL** [comment]
In order to calculate correctly the production ratios, convert all units as you are doing so far except of the productions units.

This only has to be apply when the EMSA calculates the ratios.

So in the next table, only the bold remarked units has to be fixed to the units set by the users without doing any conversion, if a user sets 1000oz (production) and 10MWh (Global Energy consumption), EMSA must convert the energy factor to kWh and the ratio would be 10000kWh/1000oz (kWh/oz )(Converted Energy Unit/ Original production unit)


Description | Ratio (yearly) 
-- | -- 
Global Energy   consumtion per production unit | kWh/**production**
Global   Electricicty comsumtion per production unit | kWh/**production**
Global Fuel   comsumtion per production unit | kWh/**production**
Global Water   consumtion per production unit | m3/**production**
Global Energy   cost per production unit | €/**production**
Global   Electricicty cost per production unit | €/**production**
Global Fuel   cost per production unit | €/**production**
Global Water   cost per production unit | €/**production**

**Comment by WINGSTeam** [comment]
Now the ratios are calculated as requested!
