### ISSUE TITLE
Benchmarking filter

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#14]
EMSA must display 3 drop-down menus in the “Company vs best” part of the benchmarking module.
This drop downs must something like this: 

![image](https://user-images.githubusercontent.com/33861863/33363008-c2ec7a20-d4de-11e7-89d5-21f965828264.png)

**Comment by WINGSTeam** [comment]
> EMSA must display 3 drop-down menus in the “Company vs best” part of the benchmarking module.
> This drop downs must something like this:


The 3 drop down filter for the benchmarking has been implemented in all pages.
