### ISSUE TITLE
Savings Calculation issues

### ISSUE THREAD

**Issue by WINGSTeam** [EnergyWater/EMSA#15]
From issue: https://github.com/EnergyWater/EMSA/issues/7 we have that:

> Just, consider that the savings and investments affects only to the improvements and no to the recommendations, so when a user selects an improvement and simulates, it will appear in the table with the description, savings, investments, etc. But if he selects a recommendations and simulates will appear only the description.

But for example: In the excel [_2. Heating V_ FINAL_4.xlsx](https://github.com/EnergyWater/EMSA/files/1514288/_2.Heating.V_.FINAL_4.xlsx) provided by Socamex in the FeatureCode P02E10F06, there is a recommendation text (without improvement action text) and the Savings potential is 10%. Since in this feature we have only Recommendation and no Improvement, shall we take into account the Saving potential or not?

This is an example. Similar issues may exist also in other Equip/Processes.

**Comment by david-ITCL** [comment]
The definition of recommendation says that it is an action whose impact cannot be calculated by the EMSA because it requieres a further study by the Energy Angel, so, if a %saving is determined for that, we have two options:
1. Remove the %saving and maintain it as a recommendation
2. Become an improvemetn action

We will need the @SOCAMEX review to clarify this.

**Comment by SOCAMEX** [comment]
Option 1: %saving and maintain it as a recommendation

It's impossible by the EMSA know how properly is the insulation, no quantification is possible

**Comment by WINGSTeam** [comment]
@SOCAMEX  Ok. Could you please clarify which savings we shall remove from the database? (e.g. from Equipment 'X' we remove the saving from Feature Code 'F10' etc.)

**Comment by SOCAMEX** [comment]
The equipment I BOILER and the saving potencial% to be removed is T14

**Comment by WINGSTeam** [comment]
@SOCAMEX So we will not take into account the savings for **all** the equipment and processes recommendations ?

**Comment by SOCAMEX** [comment]
Correct, they are recommendations that needs further evaluation by an Energy Angel to fix correct value
