### ISSUE TITLE
Equipment, process and scenario name wrongly associated

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#19]
EMSA is displaying wrongly the equipments, process and scenario name according with the scenario we are working on when we compare a scenario with the best.
Any time after selecting the efficiency tab, the scenario directly transforms to the "Meat Industry" Scenario of the EMSA trainings.

![image](https://user-images.githubusercontent.com/33861863/33937903-8ef840d2-e005-11e7-87bc-08f20aab7b54.png)

![image](https://user-images.githubusercontent.com/33861863/33937922-a31c0792-e005-11e7-9d9c-15a5918560fe.png)

This is happening in all my scenarios.

**Comment by WINGSTeam** [comment]
> EMSA is displaying wrongly the equipments, process and scenario name according with the scenario we are working on when we compare a scenario with the best.
> Any time after selecting the efficiency tab, the scenario directly transforms to the "Meat Industry" Scenario of the EMSA trainings.
>  
> This is happening in all my scenarios.

Thanks for this! It is fixed now.
