### ISSUE TITLE
Process and Equipment charts --> Show all real values and ratios from Scenarios 

### ISSUE THREAD

**Issue by david-ITCL** [EnergyWater/EMSA#2]
## Sub task 1: 
Show correctly all the existent ratios, there are some specific ratios of the process and equipments that are not been shown in the EMSA.
As an example:
![image](https://user-images.githubusercontent.com/33861863/33162489-ffcbbf1e-d029-11e7-9dbf-72def6af87a9.png)

## Sub task 2: 
Show Energy Efficiency ratio properly
![image](https://user-images.githubusercontent.com/33861863/33161714-ac41a7fe-d025-11e7-96cb-8d81ce3c5e31.png)

**Comment by david-ITCL** [comment]
As a reminder, please take into account the following document, where we define the indicators that define the efficiency of each process and equipment
[__0_Indicators Summary Table v1.xlsx](https://github.com/EnergyWater/EMSA/files/1500974/__0_Indicators.Summary.Table.v1.xlsx)

**Comment by WINGSTeam** [comment]
Thanks for the excel but it seems that there are some mistakes at the "Process Ratio" tab for the "Other" column. Could you recheck the excel?

**Comment by AaronITCL** [comment]
We didn´t find any problem in the Excel, if it is possible, could you specify your problem?
By the way, we attach an updated version of the excel with more information in empty cells which not affects directly to the ratios.
Take into account that not all process or  equipments have ratios.
[__0_Indicators Summary Table v1.xlsx](https://github.com/EnergyWater/EMSA/files/1500973/__0_Indicators.Summary.Table.v1.xlsx)

**Comment by WINGSTeam** [comment]
Please keep a versioning (V1, V2, etc..) in order to be able to compare the two excels for differences when we implement them to the databases. So we need to implement the New file from the beginning or just introduce the new information of the cells ?  
[__0_Indicators.Summary.Table.v1-ITCL(NEW).xlsx](https://github.com/EnergyWater/EMSA/files/1501163/__0_Indicators.Summary.Table.v1-ITCL.NEW.xlsx)
[_0_Indicators.summary.table.v1-ITCL(OLD).xlsx](https://github.com/EnergyWater/EMSA/files/1501164/_0_Indicators.summary.table.v1-ITCL.OLD.xlsx)

The mistake i mentioned earlier correspond to the cells J,K-5,6  witch are the same as J,K-8,9

**Comment by AaronITCL** [comment]
We find the mistake, you can find it solved in this new version.
The only differences between the old file and this new one, are some appreciable changes in the fourth column and the correction.
[_0_Indicators.Summary.Table.v2.xlsx](https://github.com/EnergyWater/EMSA/files/1501387/_0_Indicators.Summary.Table.v2.xlsx)

**Comment by WINGSTeam** [comment]
We have implement all the changes

**Comment by AaronITCL** [comment]
We miss some ratios, for example, the heating process´ results are showing only 4 ratios, but for this process there were defined 2 more ratios ("Steam production" ratio and "Energy/Steam ratio"), so for this process we miss 2 charts, it´s important that this works for all ratios for each process and ratio.

Furthermore, we realise, validating these changes, that the results, for instance of the efficiency questions, are updated only when a user submits the efficiency questions of the scenarios´ module , and not when he submits the scenario itself.
So, could you apply the submit scenario also as a global update tool for these code changes?

**Comment by WINGSTeam** [comment]
> We miss some ratios, for example, the heating process´ results are showing only 4 ratios, but for this process there were defined 2 more ratios ("Steam production" ratio and "Energy/Steam ratio"), so for this process we miss 2 charts, it´s important that this works for all ratios for each process and ratio.

I have done all the appropriate updates that i did not include on the live tool, please check if it corresponds to the requirements.

> Furthermore, we realise, validating these changes, that the results, for instance of the efficiency questions, are updated only when a user submits the efficiency questions of the scenarios´ module , and not when he submits the scenario itself.
> So, could you apply the submit scenario also as a global update tool for these code changes?

I will try to check if those changes can be made without any problems to the online version.

**Comment by AaronITCL** [comment]
Please, from now, could you implement, in the online version, all the updates you include in the tool?, so we can validate them and close the issue.
On the other hand, currently the ratios are correctly implemented.

**Comment by AaronITCL** [comment]
Scale problem in the Energy efficiency ratio´s chart has appeared, could you make the charts auto scalables?

![image](https://user-images.githubusercontent.com/33861863/33423470-3dbf9ffe-d5b9-11e7-8371-0e199e02dae5.png)

**Comment by WINGSTeam** [comment]
> Scale problem in the Energy efficiency ratio´s chart has appeared, could you make the charts auto scalables?

They are auto scalable and updated to the specific values each time when you choose an equipment. It cannot be modified further than that.
