### ISSUE TITLE
Ratios´ ranking order

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#20]
EMSA is displaying the higher ratio as TOP 1 but the best ratio is the lower one in all general ratios.

![image](https://user-images.githubusercontent.com/33861863/33939035-e75c0cc8-e009-11e7-88e1-acd1f8521f9e.png)

So the ranking must be displayed upside down.

**Comment by WINGSTeam** [comment]
> EMSA is displaying the higher ratio as TOP 1 but the best ratio is the lower one in all general ratios.
> So the ranking must be displayed upside down.

Fixed the displaying order! 
(just have in mind that because of the testing scenarios etc. the values are not normal and some times lower than 0.000001 and when they are rounded (to 5 decimals) they appear to be as 0)

**Comment by AaronITCL** [comment]
There is a similar problem with the order of the values of the equipment and  process ratios.

![image](https://user-images.githubusercontent.com/33861863/34256357-27327cdc-e655-11e7-927c-6171cfca8e68.png)

**Comment by WINGSTeam** [comment]
> There is a similar problem with the order of the values of the equipment and process ratios.

The order has change.
