### ISSUE TITLE
Score displaying -> Water drop

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#21]
In the scenario vs scenario option, appears the old version display bar, it must be a water drop.

![image](https://user-images.githubusercontent.com/33861863/33939835-f1da83e8-e00c-11e7-8b3c-6b60e333dc03.png)

**Comment by WINGSTeam** [comment]
> In the scenario vs scenario option, appears the old version display bar, it must be a water drop.

Fixed and now it displays the water Drops.
