### ISSUE TITLE
Rounding score problems

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#22]
EMSA **Scores** are displaying completely rounded in the benchmarking´s  tables, as you can see in the following image.
These scores must appear with at least 2 decimals. (This is open to discussion)

![image](https://user-images.githubusercontent.com/33861863/33979823-5dd27d1e-e0a6-11e7-860a-21d9f5428c43.png)

So, just round all the **scores** in the **tables** and **charts** of the benchmarking module to 2 decimal.

**Comment by WINGSTeam** [comment]
> EMSA Scores are displaying completely rounded in the benchmarking´s tables, as you can see in the following image.
> These scores must appear with at least 2 decimals. (This is open to discussion)
> So, just round all the scores in the tables and charts of the benchmarking module to 2 decimal.

Fixed the rounding to 2 decimals, now only if the value is e.g.  55.70 it will automatically displayed as 55.7
![screen shot 2017-12-14 at 12 26 42](https://user-images.githubusercontent.com/33901428/33987687-75da1934-e0ca-11e7-8165-3d7a2722607f.png)

@AaronITCL what should we display at the titles at the top of the page ? Should we have the values displayed with the 2 decimals as well or leave it as it is ?
![screen shot 2017-12-14 at 12 27 17](https://user-images.githubusercontent.com/33901428/33987831-ff3fd02e-e0ca-11e7-8259-09c0b179a66b.png)

**Comment by AaronITCL** [comment]
> @AaronITCL what should we display at the titles at the top of the page ? Should we have the values displayed with the 2 decimals as well or leave it as it is ?

@WINGSTeam, currently that part is ok.

**Comment by AaronITCL** [comment]
In the Scenario vs other Scenario section, there is a problem with the units.

![image](https://user-images.githubusercontent.com/33861863/33990875-c31b3f32-e0cc-11e7-9429-4b65cbdd3de5.png)

**Comment by WINGSTeam** [comment]
> In the Scenario vs other Scenario section, there is a problem with the units.

Fixed it as well with 2 decimals !
