### ISSUE TITLE
Edits in 'Information' require re-acceptance into the network

### ISSUE THREAD

**Issue by CarbonTrust1** [EnergyWater/EMSA#24]
Whether logged-in as an EA or a Company, editing information, e.g. a change of telephone number and clicking 'Submit information' in the 'Information' section of the tool results in the user being locked-out of the network until the administrator has approved the change. No warning of this is given, which is frustrating for the user. We would suggest that users should be able to edit most (if not all) of their information without requiring administrator approval.

**Comment by WINGSTeam** [comment]
> Whether logged-in as an EA or a Company, editing information, e.g. a change of telephone number and clicking 'Submit information' in the 'Information' section of the tool results in the user being locked-out of the network until the administrator has approved the change. No warning of this is given, which is frustrating for the user. We would suggest that users should be able to edit most (if not all) of their information without requiring administrator approval.

A Warning has been added more than a month ago when we receive your comments for the first time.
