### ISSUE TITLE
'Information' - data entry checks/formatting

### ISSUE THREAD

**Issue by CarbonTrust1** [EnergyWater/EMSA#25]
It appears you can insert any sort of data without having a check, i.e. VAT registration number can be only 1 digit – if this tool aims for just European countries, the format of VAT reg # for each country could be registered and after selecting the country this could be crosschecked.

**Comment by WINGSTeam** [comment]
We couldn't find a specific VAT format for the EU countries but we saw at vatlive.com that the VT numbers have a lower character length of 8 so we just introduced a minimum value for the VAT number.
