### ISSUE TITLE
Results module - scores not calculating/being displayed

### ISSUE THREAD

**Issue by CarbonTrust1** [EnergyWater/EMSA#27]
By entering the information from the case study example I get a score of 50/100 for ‘Management’ and a Benchmarking Score of 67.6% - 62/100 for ‘Enablers Score’ and 39/100 for Results score’. The tool is still returning an Efficiency Score of 0/100 and a Benchmarking Score of 0. The water drop on the General results page is displayed as empty despite an EMSA Score of 15/100 being displayed above it.

**Comment by WINGSTeam** [comment]
Maybe is an old comment because now we do not see any of these problems. As for the water drop you can see the issue 1 for more information https://github.com/EnergyWater/EMSA/issues/1
