### ISSUE TITLE
Cost against production figures

### ISSUE THREAD

**Issue by CarbonTrust1** [EnergyWater/EMSA#28]
Cost against production units are shown as Euros/kWh and there is no way for UK users to convert to £/kWh in the tool.

**Comment by WINGSTeam** [comment]
> Cost against production units are shown as Euros/kWh and there is no way for UK users to convert to £/kWh in the tool.

This was provided by partners from the start of the project/development, so the tool is designed to work with these specifications (i.e. the tool converts every value to the "base one", £ to Euro and $ to Euro depending on the date you insert to the tool)
