### ISSUE TITLE
Chart's scales

### ISSUE THREAD

**Issue by david-ITCL** [EnergyWater/EMSA#3]
Chart´s scale is wrongly implemented, a proposal is to separate these ratios into different charts, like it is shown in the image below.
![image](https://user-images.githubusercontent.com/33861863/33128464-c89f71c2-cf8c-11e7-8ac5-a9ead30c58f2.png)
![image](https://user-images.githubusercontent.com/33861863/33128485-e0dbe036-cf8c-11e7-8da1-882cf54ee604.png)
![image](https://user-images.githubusercontent.com/33861863/33128495-e424ecba-cf8c-11e7-99f8-82a35812f45b.png)

**Comment by WINGSTeam** [comment]
How shall we split the chart of the processes? Because there we have: Energy Efficiency Ratio, Production Ratio, Energy Ratio , Water Consumption Ratio.

**Comment by david-ITCL** [comment]
They correspond to very different magnitudes so, at the moment, they should be splitted on a different chart each one and later we can discuss about merge them or not.

**Comment by WINGSTeam** [comment]
We have split the charts from one that was until today to 3 for equipment and 4 for processes plus an extra  one when there is an indicator enabled for the specific equipment or process.
