### ISSUE TITLE
Doble confirmation problem

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#31]
There are some problems in the EMSA that need a doble confirmation to proceed in the EMSA, I checked this in 2 different parts of the EMSA.

- RESULTS MODULE: At the efficiency part, when a user creates a new scenario and check the Results for first time (without submitting the scenario) we can see this:

![image](https://user-images.githubusercontent.com/33861863/34103048-9b768c44-e3eb-11e7-9e84-6635e2f9ce5b.png)

When the user goes back and resubmit the efficiency questions part:

![image](https://user-images.githubusercontent.com/33861863/34103076-bb441852-e3eb-11e7-860f-daf585d2ba4c.png)

Next, if he access again to the results module, this time the results are correct

![image](https://user-images.githubusercontent.com/33861863/34103259-67464986-e3ec-11e7-99a4-34b6076d574c.png)

- COMPANY´S MODULE (EA page): When an EA tries to go to a company´s page from its correspondant module, EMSA ask him again his user and password, when he does, EMSA displays again the company´s module, if he tries again EMSA will ask the user and password, but if he goes back, then enter again to the module and goes to a company´s page, EMSA will let him access.
To clarify this, check the following image.

![image](https://user-images.githubusercontent.com/33861863/34104066-54b5b830-e3ef-11e7-91ab-53b565b19616.png)
![image](https://user-images.githubusercontent.com/33861863/34104080-64dd051a-e3ef-11e7-8c97-12eab5f1a3af.png)
![image](https://user-images.githubusercontent.com/33861863/34104092-6d5c90a2-e3ef-11e7-8d03-5ce4d0876115.png)
This is a weird bug, sometimes I just need to try to access to the company´s page after EMSA ask for my account.

**Comment by WINGSTeam** [comment]
The first problem is fixed. And for the second we are not able to replicate the issue.

**Comment by AaronITCL** [comment]
I will reopen this issue because it is happening again.

- COMPANY´S MODULE (EA page): When an EA tries to go to a company´s page from its correspondant module, EMSA ask him again his user and password, when he does, EMSA displays again the company´s module, if he tries again EMSA will ask him the user and password again, we can not access to the Company´s page in no way.
To clarify this, check the following image.

![image](https://user-images.githubusercontent.com/33861863/34104066-54b5b830-e3ef-11e7-91ab-53b565b19616.png)

**Comment by WINGSTeam** [comment]
> COMPANY´S MODULE (EA page): When an EA tries to go to a company´s page from its correspondant module, EMSA ask him again his user and password, when he does, EMSA displays again the company´s module, if he tries again EMSA will ask him the user and password again, we can not access to the Company´s page in no way.
> To clarify this, check the following image.

We fixed the problem. Now, if you choose an assigned company from an angel account, you automatically have access to this company's account. Please, check this issue from your account as well and let us now if it works.
