### ISSUE TITLE
 Efficiency Benchmarking Scenario vs Scenario

### ISSUE THREAD

**Issue by WINGSTeam** [EnergyWater/EMSA#32]
@david-ITCL, @AaronITCL How should we display all the values of the equipment and processes of the two selected scenarios at this page?

**Comment by AaronITCL** [comment]
EMSA just must let the user compare between equipments or processes by the ratios when he selects them.
The only condition is to compare equipment-equipment and process-process (Can´t be process-equipment)

**Comment by WINGSTeam** [comment]
So there is no problem if the two scenarios have different equipment or processes ?

**Comment by AaronITCL** [comment]
There will be not problem if that happens, the user choose which scenarios he wants to compare between.

**Comment by WINGSTeam** [comment]
Thanks!

**Comment by AaronITCL** [comment]
We can´t see any results on the benchmarking efficiency  vs other scenario.
