### ISSUE TITLE
SQL problem Efficiency Questions

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#33]
EMSA is displaying a Sql warning message when a user submits the efficiency questions.

![image](https://user-images.githubusercontent.com/33861863/34196257-970f0790-e561-11e7-839f-d1205224c125.png)
This only happens in a scenario that I create today.

**Comment by WINGSTeam** [comment]
Could you please check again if it shown now? Thanks!

**Comment by AaronITCL** [comment]
It is ok now, thanks!!.
