### ISSUE TITLE
Total energy consumption savings calculation

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#34]
Currrently EMSA is using the Global Energy Price ratio to transform the Total energy cost to euros, but the calculation must be the Electricity cost + Fuel cost, as you are doing with the CO2 emmisions.

![image](https://user-images.githubusercontent.com/33861863/34201031-825018be-e573-11e7-8680-0b0eab07179f.png)

As you can see in the image, as a visual example of 1 cell, the Total energy cost=396934.5 €/year, the Fuel cost = 338788.2 €/year and the Electricity cost =0 €/year, so Total energy cost=Electricity cost+ Fuel cost, 396934.5 !=  338788.2 + 0, so this is wrong, the Total energy cost must be 338788.2 + 0 = 338788.2

**Comment by WINGSTeam** [comment]
The calculations have been change to the specified one.
