### ISSUE TITLE
Benchmarking best company´s score

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#35]
A zero score can´t be the best score:

![image](https://user-images.githubusercontent.com/33861863/34244530-eeb4dc30-e625-11e7-9b90-41edd337decc.png)

**Comment by WINGSTeam** [comment]
This is the same issue that we have discussed with the values that are lower than 0.00001 and with the rounding process become 0.

**Comment by AaronITCL** [comment]
Ok, hope so after the benchmarking reboot will not exists any ratio that be rounded by 0 (because that would be confuse) so if in the future this tiny ratio values are common we will need to increment this rounding mechanism to more digits
