### ISSUE TITLE
Wrong Total energy consumption savings calculation 2

### ISSUE THREAD

**Issue by SOCAMEX** [EnergyWater/EMSA#37]
There is some problems with the interpolation of the saving calculations with an equipment with respect the global scenario (installation).
The process improvements suggested by the tool in relation to the pumping of sludge purges are the following:
![picture1](https://user-images.githubusercontent.com/33928557/34265205-905ff5ca-e675-11e7-9354-fa8533ae0ea5.jpg)
RESULTS OBTAINED AFTER SELECTING ALL ACTIONS AND RECOMMENDATIONS FOR IMPROVEMENT
![picture2](https://user-images.githubusercontent.com/33928557/34265366-ed949368-e675-11e7-9bd1-764212632aaf.jpg)
The tool calculates that the savings from the implementation of only the improvement actions and recommendations of the sludge purge would produce a saving of 50% of the total energy consumption of the entire scenario. That is a WRONG interpolation
To evaluate the breakdown of total energy savings, the tool allows us to see the impact of each measure. The only measures that have an impact on energy saving according to the tool are respective to the pump equipment and are the following and the are correct
![picture3](https://user-images.githubusercontent.com/33928557/34265492-4e5abbaa-e676-11e7-94c9-95a9dc97fac0.jpg)
The specific impact of each measure is well calibrated. In the column "Energy Savings" you can see the savings in kWh / year, and they are savings that adjust to the consumption of that equipment.
However, there is a mismatch between the summary of results and the specific impacts, since the savings go from being 504 kWh / year (adding all the specific savings of each improvement) to 58,002 kWh / year (according to the summary).

**Comment by WINGSTeam** [comment]
Thanks for the comment.
So if we understand correctly, in the Table that you show above "Total energy consumption"  the total energy consumption should go from 116941 kWh / year to 116437 (which is 116941-504). Similarly the total energy cost will be reduced according to the values in the column 'Cost saving' etc.  

If the understanding is correct, then we will show the results as mentioned in the paragraph above.

**Comment by WINGSTeam** [comment]
@SOCAMEX  We have implement the changes you specified, could you please take a look and report back ?

**Comment by WINGSTeam** [comment]
@SOCAMEX  We have found a problem regarding the changes that we have made:
Specifically, now that the savings are calculated on the summation of the values of one by one improvement that the user has selected, the savings percentages are some times more than 100% and that means that the new values are negative.

For example we have selected these improvements for the pumping (and other improvements from other processes/equipment) from the CP1 test scenario:
![improvements-pumping](https://user-images.githubusercontent.com/33901428/34528397-8628a746-f0b1-11e7-8c50-b41a4873ff07.PNG)

So now the results are not correct as you can see in the picture below:

![results](https://user-images.githubusercontent.com/33901428/34528473-b9f02cca-f0b1-11e7-8da9-bd4d31ba1878.PNG)

**Comment by WINGSTeam** [comment]
Simulator is fully functional!
