### ISSUE TITLE
Database Question

### ISSUE THREAD

**Issue by WINGSTeam** [EnergyWater/EMSA#38]
@david-ITCL  At the Cooling_V_FINAL_2 Excel  (number 5) for the Chiller there are two columns that have the same name "Equation" which is the correct column for the F22 and F24 ? The column M or N or we need them both?

**Comment by AaronITCL** [comment]
@WINGSTeam , Cooling process has been updated to its 3th version, it is attached to this message, you can check it also in the "Projectplace".

[5. Cooling V_FINAL_3.xlsx](https://github.com/EnergyWater/EMSA/files/1666943/5.Cooling.V_FINAL_3.xlsx)

**Comment by WINGSTeam** [comment]
@AaronITCL we have found one more problem regarding the excel provided by Socamex.

At the excel 24. Pre-treatment V_FINAL , the equipment, at the equipment " SAND CLASSIFIER "  at line 21 the column M . The equation does not seems right "P10E39F12   = P10E39F09 / P10E39F11".

Plus the Feature Code "P24E24F13" appears two times , so we created a new feature with the last question at line 23.

**Comment by WINGSTeam** [comment]
@AaronITCL 
One more at 4. Boiling V_FINAL , at equipment "CONDENSER" lines 16-17 column L also are not correct because you cannot ask about a result of a question that you are currently asking (or maybe in general are not correct). 
What should we do ?

**Comment by WINGSTeam** [comment]
@AaronITCL @david-ITCL 
Except the two previous questions. There is another one at 4. Boiling V_FINAL , for the process Boiling at line 29 , with Feature Code "P04F27" , column "H" has "Result", but column "I" and "L" have both  "P04F27=   Ask" as value. What should we display, calculate etc on this feature ?

**Comment by AaronITCL** [comment]
@WINGSTeam, first of all, sorry for the delay.

> @AaronITCL we have found one more problem regarding the excel provided by Socamex.
> At the excel 24. Pre-treatment V_FINAL , the equipment, at the equipment " SAND CLASSIFIER " at line 
> 21 the column M . The equation does not seems right "P10E39F12 = P10E39F09 / P10E39F11".

We have deleted the "Equation" cell of the Feature Code P24E24F16

> Plus the Feature Code "P24E24F13" appears two times , so we created a new feature with the last question at line 23.

Feature Code has been changed to P24E24F17, if you have change this code to another one, please tell us.

> @AaronITCL
> One more at 4. Boiling V_FINAL , at equipment "CONDENSER" lines 16-17 column L also are not correct because you cannot ask about a result of a question that you are currently asking (or maybe in general are not correct).
> What should we do ?

> @AaronITCL @david-ITCL
> Except the two previous questions. There is another one at 4. Boiling V_FINAL , for the process Boiling at line 29 , with Feature Code "P04F27" , column "H" has "Result", but column "I" and "L" have both "P04F27= Ask" as value. What should we display, calculate etc on this feature ?
> 

For this questions an answer of  @SOCAMEX would be better.

You can find the changes in the following excel, also updated in the projectplace.

[24. Pre-treatment V_FINAL_2.xlsx](https://github.com/EnergyWater/EMSA/files/1684534/24.Pre-treatment.V_FINAL_2.xlsx)

**Comment by WINGSTeam** [comment]
At "28. Anaerobic Biological Treatment V_FINAL" excel could you please check all the equations and the "if" statements? We think that most of them are not correct. 
Thanks!

**Comment by AaronITCL** [comment]
We have make some changes in that process, you can find them in the following excel.

[28. Anaerobic Biological Treatment V_FINAL_2.xlsx](https://github.com/EnergyWater/EMSA/files/1695067/28.Anaerobic.Biological.Treatment.V_FINAL_2.xlsx)

**Comment by WINGSTeam** [comment]
At cooling process the Feature Code P05F01 has a recommended value but at the "keyfactor" column the value is "NO".  We think that maybe this is wrong, because only the "KeyFactor" features can have a recommended value. Could you please check it ?

Also at Cataphoresis Baths process , at Feature code P08F03 there is the same issue, the Keyfactor is "No"  but it has a recommended value.

**Comment by AaronITCL** [comment]
That must not be a significative problem for the EMSA´s funcionality, but if this features are a problem for the code configuration in any way , just say us what type of problem is, so we could decide what to do.

**Comment by WINGSTeam** [comment]
We think it is a problem because it changes how the score is measured for the specific process, for example if a feature code is a key factor and has a recommended value then we count it and create a score at the end. But if a feature code has a key factor but does not have a recommended value, then it does not taken into account and not measured by the tool so the overall score changes.

**Comment by AaronITCL** [comment]
For now, consider this as correct, so if it doesn´t count for the score will be OK even if it has a recommended value.
