### ISSUE TITLE
Correction from Greenflex

### ISSUE THREAD

**Issue by cbarbaux** [EnergyWater/EMSA#42]
Dear all,

Please find attached our comment ,

[EMSA tool Correction V2.docx](https://github.com/EnergyWater/EMSA/files/1743683/EMSA.tool.Correction.V2.docx)

Best regards.

**Comment by WINGSTeam** [comment]
[EMSA tool Correction V2-Wings.docx](https://github.com/EnergyWater/EMSA/files/1794102/EMSA.tool.Correction.V2-Wings.docx)

You will find  updates  and comments in the attachment.
