### ISSUE TITLE
CORRECTION BY SOCAMEX (PARTIAL)

### ISSUE THREAD

**Issue by SOCAMEX** [EnergyWater/EMSA#44]
To the moment we have found the following mistakes. We are still doing the review.

[Process-Equipment follow-up 23FebSOCAMEX.xlsx](https://github.com/EnergyWater/EMSA/files/1751064/Process-Equipment.follow-up.23FebSOCAMEX.xlsx)

**Comment by WINGSTeam** [comment]
The mistakes are fixed now.
