### ISSUE TITLE
1.1. Pumps

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#47]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

### 1. Answer issue
![image](https://user-images.githubusercontent.com/33861863/36666510-360c66bc-1aeb-11e8-9ec3-f6634df93b5e.png)
For this question a YES/NO answer can´t be possible, so change the answer to a numerical one, for the units maybe @SOCAMEX can help us.
## Ratio´s calculations
Correctly implemented
## Energy improvements identification
As it happens in other process and equipments when I set all recommended values in EMSA efficiency questions, EMSA displays almost all the recommendations and issues and that is wrong.

In the following table you can find the issues and the codes that are referenced to:

Type of issue | Improvements | Recommendations
-- | -- | --
Doesn´t   appears | P01E01F06,   P01E01F12, P01E01F44 | P01E01F25 ,   P01E01F44
Appears in recommendation when is an improvement or viceversa |   | P01E01F38, P01E01F50
Gramatical or implementation issue |   |  

## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
In the type of pump tab from the  Pumping V_Final_2 excel, row 9, column C is empty and the value in row 10, column C does not exist in P01E01F44 list of values. Also, in row 16 column E, what is the nominal heater pressure? The nominal boiler pressure and nominal steam production as well.

**Comment by WINGSTeam** [comment]
@AaronITCL @david-ITCL Reviewing the type pump tab from the Pumping V_Final_2 excel, we found some more uncertainties. First, the contents in column B (pump type), are not exist in any question on equipment Pump. Also, in column C there are some empty rows. In column E, rows 15 and 16, the nominal heater pressure and the nominal boiler pressure are unclear. So, could you please review this particular tab and give us an update?

**Comment by AaronITCL** [comment]
> In the type of pump tab from the Pumping V_Final_2 excel, row 9, column C is empty.

Maybe @SOCAMEX can help us with this. 

> Reviewing the type pump tab from the Pumping V_Final_2 excel, we found some more uncertainties. First, the contents in column B (pump type), are not exist in any question on equipment Pump. Also, in column C there are some empty rows

We can add this new uses to P01E01F44, could you help us with this issue  @SOCAMEX?

> Also, in column C there are some empty rows. In column E, rows 15 and 16, the nominal heater pressure and the nominal boiler pressure are unclear. So, could you please review this particular tab and give us an update?

Nominal Heater pressure appears in P01E01F53 (if I select Fire-tube boiler water feeding use) 
Nominal Boiler pressure appears in P01E01F53 (if I select Heater water feeding use)  

![image](https://user-images.githubusercontent.com/33861863/36785108-0ce7d8dc-1c82-11e8-9e3a-68ba72c82b29.png)

![image](https://user-images.githubusercontent.com/33861863/36784749-db344e5c-1c80-11e8-8d18-9b920b8f3745.png)

**Comment by WINGSTeam** [comment]
We are waiting for SOCAMEX to answer on this, for implementing the final version of the equipment pump.

**Comment by WINGSTeam** [comment]
> Reviewing the type pump tab from the Pumping V_Final_2 excel, we found some more uncertainties. First, the contents in column B (pump type), are not exist in any question on equipment Pump. Also, in column C there are some empty rows

Do we have a final answer regarding this ?
