### ISSUE TITLE
1.2. Piping

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#48]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

### 1. Answer issue
Correctly implemented
## Ratio´s calculations
Correctly implemented
## Energy improvements identification
As it happens in other process and equipments when I set all recommended values in EMSA efficiency questions, EMSA displays almost all the recommendations and issues and that is wrong.

In the following table you can find the issues and the codes that are referenced to:

Type of issue | Improvements | Recommendations
-- | -- | --
Doesn´t   appears | P01E02F13, P01E02F14|
Appears in recommendation when is an improvement or viceversa |   | 
Gramatical or implementation issue |   |  
## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
Improvements and Recommendations for P01E02F13 and  P01E02F14 fixed.
