### ISSUE TITLE
Management´s improvements display

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#5]
Based on the attached document, EMSA must display the pertinant improvements according to the managment values set on the scenario.

_Note: Currently this issue appears in the new created scenarios, in the old ones this is not happening_

[CRITERIA IMPROVEMENTS - V4.xlsx](https://github.com/EnergyWater/EMSA/files/1508859/CRITERIA.IMPROVEMENTS.-.V4.xlsx)

**Comment by WINGSTeam** [comment]
We have fixed the specific bug and now is working again.

**Comment by AaronITCL** [comment]
2.4. Water and Energy subcriteria´s Plan is displaying wrongly its 2nd score.
As you can see in the image, EMSA is displaying 2nd and 3th Score in the same text box.

![image](https://user-images.githubusercontent.com/33861863/33543878-fd4200ac-d8d8-11e7-9a43-8fa660cae9f7.png)

**Comment by WINGSTeam** [comment]
> 2.4. Water and Energy subcriteria´s Plan is displaying wrongly its 2nd score.
> As you can see in the image, EMSA is displaying 2nd and 3th Score in the same text box.

Fixed!
