### ISSUE TITLE
EMSA Lite equipments improvements issue

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#50]
Checking the EMSA Lite improvements actions module, we realise that we can not check (by clicking on them), the improvements of the equipments, seems that they are disabled.

![image](https://user-images.githubusercontent.com/33861863/36716038-2cc351de-1b99-11e8-8f54-40e9e8bd89b6.png)

**Comment by Matilde-SmartFuture** [comment]
In addiction I can say that by checking the process Improvement Actions, sometimes the list of equipment related to that process are not displayed in the Recommendations table
![immagine](https://user-images.githubusercontent.com/33963050/36723815-95b06f3e-1bb1-11e8-8306-53ce1eed671f.png)
