### ISSUE TITLE
P29 Refining treat_scenario+results

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#51]
[P29 Refining treat_scenario+results_SMART FUTURE.xlsx](https://github.com/EnergyWater/EMSA/files/1762162/P29.Refining.treat_scenario.results_SMART.FUTURE.xlsx)

**Comment by WINGSTeam** [comment]
Fixed.
Also for the units : 
P29F15 -> gal/h,   gal/min, gal/s are missing
P29F17 -> what's the needing of   1k and 10k units?
The unts where implemented based on provided requirements and for flow conversion there was not a gal to liter conversion and also for the production was the same with 1000 and 10000 given for the units.
