### ISSUE TITLE
2. Heating

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#58]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

### 1. Missing recommended value

Please @SOCAMEX could you help us to solve this issue?

![image](https://user-images.githubusercontent.com/33861863/36961905-9e5ee322-204d-11e8-8f3b-a436e1395f73.png)

### 1. Missing steam related ratios in charts
![image](https://user-images.githubusercontent.com/33861863/36961994-02fff7c6-204e-11e8-95f1-ac92df2c3851.png)

### 2. Calculation issue
Production ratio has the same value as energy ratio when it must not, in this case the production ratio should be 4,281 and it appears 3,424, the value of the Energy ratio.
![image](https://user-images.githubusercontent.com/33861863/36962043-3331dc5c-204e-11e8-87f3-dd5f944e7b70.png)

### 3. Missing question and working hours question issue
We miss, between Feature Code P02F20 and P02F21, a question. 
This is how the EMSA is displaying this questions now:
![image](https://user-images.githubusercontent.com/33861863/36968006-96a971e2-2061-11e8-8f19-3271c3d0b709.png)

Our proposal is to add a new question and changing the working hours condition:
![image](https://user-images.githubusercontent.com/33861863/36974282-6bde6192-2076-11e8-9a05-151ede32ed5e.png)

### 4. Label of the ratios issue.
We miss recommended value and recommendation in P02F16 and P02F25

- The **Recommended value** should be "MEASURED"  

- The **Recommendation**  should be "Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the pumping process, such as  water flow and water consumption"

## Energy improvements identification
In validation process
## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
> 1. Missing steam related ratios in charts

Done

> 2. Calculation issue

Done


> 4. Label of the ratios issue.

Done

> 3. Missing question and working hours question issue

Done

**Comment by AaronITCL** [comment]
I make a mistake in this type of issues, the change is marked in bold, please check it again
### 4. Label of the ratios issue.
We miss recommended value and recommendation in P02F16 and P02F25

- The Recommended value **for both** should be "MEASURED"  

- **For P02F16** The Recommendation  should be **"Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the heating process, such as energy consumption, water flow, production"**

- **For P02F25** The Recommendation should be "Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the **heating** process, such as  water flow and water consumption"

**Comment by WINGSTeam** [comment]
> I make a mistake in this type of issues, the change is marked in bold, please check it again
> 
> 4. Label of the ratios issue.
> We miss recommended value and recommendation in P02F16 and P02F25
> 
> The Recommended value for both should be "MEASURED"
> 
> For P02F16 The Recommendation should be "Consider installing measurement equipments in all the main parameters that affect the energy efficiency from the heating process, such as energy consumption, water flow, production"
> 
> For P02F25 The Recommendation should be "Consider installing measurement equipments in all the main parameters that affect the energy efficiency from the heating process, such as water flow and water consumption"

Done.
