### ISSUE TITLE
2.1. Filter

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#59]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

### 1. Units issue

A pull-down selector of power units pull-down is needed in this question
![image](https://user-images.githubusercontent.com/33861863/36962146-aac60964-204e-11e8-9fd6-9218cf6426e6.png)

### 2. Proposal
Currently the excel shows the following features:
![image](https://user-images.githubusercontent.com/33861863/36962232-02ef076c-204f-11e8-9ac4-c73c1d49b6f4.png)
We propose that questions P02E04F24 and P02E04F29 activates when the filter is mechanical as it is on the P02E04F04 question.
![image](https://user-images.githubusercontent.com/33861863/36962240-0ce81164-204f-11e8-9cf0-9abc7b220b66.png)

### 1. No values in charts

![image](https://user-images.githubusercontent.com/33861863/36962278-229fa2b0-204f-11e8-97ac-490a63e386e1.png)

### 2. Calculation issue
Production ratio has the same value as energy ratio when it must not, in this case the production ratio should be 4,281 and it appears 3,424, the value of the Energy ratio.
![image](https://user-images.githubusercontent.com/33861863/36962043-3331dc5c-204e-11e8-87f3-dd5f944e7b70.png)

### 3. Missing recommended value.

Please @SOCAMEX coul you help us in this?
![image](https://user-images.githubusercontent.com/33861863/36962330-672419f2-204f-11e8-80cc-6ff60ceb4e96.png)

### 4. Label of the ratios issue.
We miss recommended value and recommendation in P02E04F19

- The **Recommended value** should be "MEASURED"  

- The **Recommendation**  should be "Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the pumping process, such as  water flow and water consumption"

## Energy improvements identification
In validation process
## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
> 1. Units issue

Done.

> 2. Calculation issue

Done

> 2. Proposal

Done

> 4. Label of the ratios issue.

Done


> 1. No values in charts

Done

**Comment by WINGSTeam** [comment]
> 1. No values in charts

Done

**Comment by AaronITCL** [comment]
I make a mistake in this type of issues, the change is marked in bold, please check it again
### 4. Label of the ratios issue.
We miss recommended value and recommendation in P02E04F19

- The Recommended value should be "MEASURED"  

- The Recommendation  should be **"Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the filter equipment, such as energy consumption and water flow"**

**Comment by WINGSTeam** [comment]
> I make a mistake in this type of issues, the change is marked in bold, please check it again
> 
> 4. Label of the ratios issue.
> We miss recommended value and recommendation in P02E04F19
> 
> The Recommended value should be "MEASURED"
> 
> The Recommendation should be "Consider installing measurement equipments in all the main parameters that affect the energy efficiency from the filter equipment, such as energy consumption and water flow"

Done

**Comment by WINGSTeam** [comment]
@AaronITCL The improvements work just fine for us. So, could you send us your user account (username, password) in order to check if there is any problem?

**Comment by AaronITCL** [comment]
### 3. Type of value issue.

This answer must be a caligrafic value, not a numerical one
![image](https://user-images.githubusercontent.com/33861863/37278448-07f4d2b6-25e8-11e8-99f0-01b023f4d8b6.png)

**Comment by WINGSTeam** [comment]
> 3. Type of value issue.
> This answer must be a caligrafic value, not a numerical one

Done!
