### ISSUE TITLE
Improvements simulation - Summary Table

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#6]
## Sub task 1 - Charts:
The values for the first chart are incorrect:

- Without selecting any saving, the EMSA is displaying a hundred value of Energy, Cost and Percent saving for the improvements selection´s bar values. 

- The chart is not showing the total saving potential.

![image](https://user-images.githubusercontent.com/33861863/33309249-b7c5c9ba-d41d-11e7-8b51-1164be8bc079.png)

A similar issue is happening to the management score and the ranking for the second chart, showing the status after the improvement actions as a fixed value of 100.

![image](https://user-images.githubusercontent.com/33861863/33309391-4d39ac5a-d41e-11e7-95a2-404558aa18d6.png)

## Sub task 2 - Documented savings values:

- The Improvement rate and  the Savings (%) must be correctly calculated, even if the result is 0, the value must be displayed.

- The savings must be separated into 2 columns, one with the real value in the correspondent units and the other with the saving´s percent

Currently:
![image](https://user-images.githubusercontent.com/33861863/33309867-f8489dda-d41f-11e7-86ae-ad69b3f9a428.png)

Please, apply the corrections to all the tables.

**Comment by WINGSTeam** [comment]
> Sub task 2 - Documented savings values:
> 
> The Improvement rate and the Savings (%) must be correctly calculated, even if the result is 0, the value must be displayed.
> 
> The savings must be separated into 2 columns, one with the real value in the correspondent units and the other with the saving´s percent

We calculate everything now even if the result is 0 and we have also split the savings into two columns.

**Comment by WINGSTeam** [comment]
> Sub task 1 - Charts:
> 
> The values for the first chart are incorrect:
> 
> Without selecting any saving, the EMSA is displaying a hundred value of Energy, Cost and Percent saving for the improvements selection´s bar values.
> 
> A similar issue is happening to the management score and the ranking for the second chart, showing the status after the improvement actions as a fixed value of 100.

The charts have been fixed to show the correct values.

**Comment by AaronITCL** [comment]
We realise that the tables have now values, but the calculations are working wrongly,  you can check it in the picture, the status after improvements actions can´t be less than the current status.

![image](https://user-images.githubusercontent.com/33861863/33826876-ab14d046-de66-11e7-956b-ef08e08305cd.png)

Furthermore the improvement rate must be a percent, calculated as:

![image](https://user-images.githubusercontent.com/33861863/33827023-220cf7b4-de67-11e7-9371-f9ff15354749.png)

**Comment by WINGSTeam** [comment]
> We realise that the tables have now values, but the calculations are working wrongly, you can check it in the picture, the status after improvements actions can´t be less than the current status.

Now is fixed, below is a screenshot of a newly created scenario. 
![screen shot 2017-12-11 at 20 18 12](https://user-images.githubusercontent.com/33901428/33846676-7df92e96-deb0-11e7-9b63-f113c85d2884.png)
