### ISSUE TITLE
2.2. Ion exchanger

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#60]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

### 1. E05F02 issue
When I set a value in this question submits and goes again to the equipment, the value has been deleted:

![image](https://user-images.githubusercontent.com/33861863/36962485-12a4c024-2050-11e8-8b38-8c48a44a3a68.png)

## Ratios calculations
Correctly implemented
## Energy improvements identification
In validation process
## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
> 1. E05F02 issue
> When I set a value in this question submits and goes again to the equipment, the value has been deleted:

Fixed!
