### ISSUE TITLE
2.3. Heater

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#61]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

### 1. Display issues
EMSA doesn´t display this questions correctly in function of the conditions imposed.

![image](https://user-images.githubusercontent.com/33861863/36962732-01c98144-2051-11e8-9635-78fb181c45cb.png)

### 2. Proposal

Currently the following question is asked depending of the type of heater, when it should be the power source
![image](https://user-images.githubusercontent.com/33861863/36962766-3066b03a-2051-11e8-895b-dde39125d482.png)
Our proposal is:
![image](https://user-images.githubusercontent.com/33861863/36962802-497928aa-2051-11e8-9423-772074f9e903.png)
Please @SOCAMEX could you validate this?

Where:
![image](https://user-images.githubusercontent.com/33861863/36962941-bc5b8fe8-2051-11e8-8e4d-d05872e29101.png)

### 3. Label of the ratios issue.
We miss recommended value and recommendation in P02E06F29

- The **Recommended value** should be "MEASURED"  

- The **Recommendation**  should be "Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the pumping process, such as  water flow and water consumption"

### 1. Missing heater efficiency ratio
![image](https://user-images.githubusercontent.com/33861863/36962963-d020d24a-2051-11e8-92e2-fc9e518ecb04.png)

## Energy improvements identification
In validation process
## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
> 1. Display issues

Done

> 3. Label of the ratios issue.

Done

> Ratio´s calculations

Done

**Comment by AaronITCL** [comment]
I make a mistake in this type of issues, the change is marked in bold, please check it again
### 4. Label of the ratios issue.
We miss recommended value and recommendation in P02E06F29

- The Recommended value should be "MEASURED"  

- The Recommendation  should be **"Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the heater equipment, such as energy consumption and water flow"**

**Comment by WINGSTeam** [comment]
> make a mistake in this type of issues, the change is marked in bold, please check it again
> 
> 4. Label of the ratios issue.
> We miss recommended value and recommendation in P02E06F29
> 
> The Recommended value should be "MEASURED"
> 
> The Recommendation should be "Consider installing measurement equipments in all the main parameters that affect the energy efficiency from the heater equipment, such as energy consumption and water flow"

Done.

**Comment by WINGSTeam** [comment]
@AaronITCL The improvements work just fine for us. So, could you send us your user account (username, password) in order to check if there is any problem?

**Comment by AaronITCL** [comment]
> Ratio´s calculations
> 1. Missing heater efficiency ratio
> ![image](https://user-images.githubusercontent.com/33861863/37769085-25302afc-2dd0-11e8-8ccd-02ce9c40e61a.png)

Still working wrongly

**Comment by WINGSTeam** [comment]
> Still working wrongly

It works fine now. You can check it as well.
