### ISSUE TITLE
3. Heat exchange

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#62]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

### 1. Missing question and working hours question issue
We miss, between Feature Code P02F20 and P02F21, a question. 
This is how the EMSA is displaying this questions now:

![image](https://user-images.githubusercontent.com/33861863/36966907-957dd6d0-205e-11e8-81b4-57779e2e6d53.png)

Our proposal is to add a new question and changing the working hours condition:

![image](https://user-images.githubusercontent.com/33861863/36974359-b15e0b1e-2076-11e8-96c2-4a8da38ccbf3.png)

### 2. Label of the ratios issue.
We miss recommended value and recommendation in P03F16 and P03F25

- The **Recommended value** should be "MEASURED"  

- The **Recommendation**  should be "Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the pumping process, such as  water flow and water consumption"

### 1. Missing ratios values and appearance of non necessary ratios
Only must appear Exchange Efficiency with its value.
![image](https://user-images.githubusercontent.com/33861863/36967008-d9ad62c6-205e-11e8-8a8d-cae627e86316.png)

## Energy improvements identification
In validation process
## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
> 1. Missing question and working hours question issue

Done.

> 2. Label of the ratios issue.

Done.

> Ratio´s calculations

Done.

**Comment by AaronITCL** [comment]
I make a mistake in this type of issues, the change is marked in bold, please check it again
### 2. Label of the ratios issue.
We miss recommended value and recommendation in P03F16 and P03F25

- The Recommended value **for both** should be "MEASURED"  

- **For P03F16** The Recommendation  should be **"Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the heat exchanger process, such as energy consumption, water flow, production"**

- **For P03F25** The Recommendation should be "Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the **heat exchanger** process, such as  water flow and water consumption"

**Comment by WINGSTeam** [comment]
Done.

**Comment by AaronITCL** [comment]
> 1. Missing ratios values and appearance of non necessary ratios
> Only must appear Exchange Efficiency with its value.

![image](https://user-images.githubusercontent.com/33861863/37769220-915c5cf0-2dd0-11e8-93ca-467fcbad1904.png)

Still working wrongly

**Comment by WINGSTeam** [comment]
> Still working wrongly

It works fine now. You can check it as well.
