### ISSUE TITLE
3.1. Heat exchanger

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#63]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

### 1. Displaying issue
This question is displaying also if P03E07F62 is not “Steam-air” or “Water-air”
![image](https://user-images.githubusercontent.com/33861863/36968698-9c793ba0-2063-11e8-997c-51263dd95706.png)

### 1. Missing ratios values and appearance of non necessary ratios
Only must appear Exchange Efficiency

![image](https://user-images.githubusercontent.com/33861863/36969508-f22b9834-2065-11e8-8ade-4db021b0b7d7.png)

## Energy improvements identification
In validation process
## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
> 1. Displaying issue

Done

> 1. Missing ratios values and appearance of non necessary ratios

Done.

**Comment by AaronITCL** [comment]
When I set a fluid like refrigerant R-717, and press submit, EMSA displays some weird information
![image](https://user-images.githubusercontent.com/33861863/37769798-7fc2a056-2dd2-11e8-866c-1101e86a183a.png)
![image](https://user-images.githubusercontent.com/33861863/37769808-88d22f2c-2dd2-11e8-8320-7d26983c8d14.png)

**Comment by WINGSTeam** [comment]
> When I set a fluid like refrigerant R-717, and press submit, EMSA displays some weird information

Fixed
