### ISSUE TITLE
4. Boiling

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#64]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

> ## Process question
> ### 1. Missing question and working hours question issue
> We miss, between Feature Code P02F20 and P02F21, a question. 
> This is how the EMSA is displaying this questions now:
> 
> ![image](https://user-images.githubusercontent.com/33861863/36974028-782c17ec-2075-11e8-8232-7b9ea8a0b8ce.png)
> 
> Our proposal is to add a new question and changing the working hours condition:
> 
> ![image](https://user-images.githubusercontent.com/33861863/36974032-7cfa0144-2075-11e8-8988-dbb8ed42584d.png)
> 
> ### 2. Label of the ratios issue.
> We miss recommended value and recommendation in P04F16 and P04F25
> 
> - The **Recommended value** should be "MEASURED"  
> 
> - The **Recommendation**  should be "Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the pumping process, such as  water flow and water consumption"
> 
> ### 3. Steam production units
> Set: Steam production (kg/h)
> ![image](https://user-images.githubusercontent.com/33861863/36974109-c33beb90-2075-11e8-9661-ef79cb09b5b8.png)
> 
> ## Ratio´s calculations
> ### 1. Missing ratios values
> ![image](https://user-images.githubusercontent.com/33861863/36974096-ba0ce7e0-2075-11e8-860e-a8a4b6c6d830.png)
> 

## Energy improvements identification

In this process the principal problem is in the simulation part, most of the improvements and recommendations are wrongly implemented, you must check it all.

When we set all the recommended values in EMSA efficiency questions, EMSA displays all the recommendations and issues.

## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
> 1. Missing question and working hours question issue

Done


> 2. Label of the ratios issue.

Done

> 3. Steam production units

Done

> 1. Missing ratios values

Done

**Comment by AaronITCL** [comment]
I make a mistake in this type of issues, the change is marked in bold, please check it again
### 2. Label of the ratios issue.
We miss recommended value and recommendation in P04F16 and P04F25

- The Recommended value **for both** should be "MEASURED"  

- **For P04F16** The Recommendation  should be **"Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the boiling process, such as energy consumption, water flow, production"**

- **For P04F25** The Recommendation should be "Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the **boiling** process, such as  water flow and water consumption"

**Comment by AaronITCL** [comment]
Adding a new issue to this process:
### 4. Recommended value issue
Add a recommended value of YES in the following question
![image](https://user-images.githubusercontent.com/33861863/37023865-85892d28-2127-11e8-9ebb-4b1244529059.png)

**Comment by WINGSTeam** [comment]
Done.

**Comment by AaronITCL** [comment]
First comment updated

**Comment by WINGSTeam** [comment]
@AaronITCL The improvements work just fine for us. So, could you send us your user account (username, password) in order to check if there is any problem?

**Comment by AaronITCL** [comment]
Sorry @WINGSTeam , this days as you know we couldn´t access to the simulation module so we couldn´t check it.
I have check it today and stills working wrongly. I will send you my user account so you can check it.

This is happening to the "Cooling", the "Boiling" and the "Ballast water and cleaning water" process.

If you check my scenario configuration, you will see that the processes and equipments are repited twice, the first one has all the non recommended values and the following one will have the recommended ones ( excepting the pump equipments that all of them except the 2 first that are created only because we need a equipment to create a process, this equipments and the boiler are empty)

The following image shows my scenario configuration so you can easily check it

![image](https://user-images.githubusercontent.com/33861863/37462154-33cd957e-2851-11e8-9fe9-16c38b63bc33.png)

![image](https://user-images.githubusercontent.com/33861863/37462161-3a78b782-2851-11e8-910e-471964f0a3c1.png)

**Comment by WINGSTeam** [comment]
Thanks for the feedback, the "Cooling", the "Boiling" and the "Ballast water and cleaning water" processes work fine now. We will check, the rest processes and equipment for the same problem.

**Comment by AaronITCL** [comment]
Just to update the information, the process are working fine but not the equipments.

**Comment by WINGSTeam** [comment]
> Just to update the information, the process are working fine but not the equipments.

Now, both processes and equipment are working fine. You can check it as well. Thanks!
