### ISSUE TITLE
5. Cooling

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#65]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

> ## Process question
> ### 1. Missing question and working hours question issue
> We miss, between Feature Code P02F20 and P02F21, a question. 
> This is how the EMSA is displaying this questions now:
> 
> ![image](https://user-images.githubusercontent.com/33861863/36974511-37d20074-2077-11e8-9520-40df45602977.png)
> 
> Our proposal is to add a new question and changing the working hours condition:
> 
> ![image](https://user-images.githubusercontent.com/33861863/36974528-433baeba-2077-11e8-9adf-1a0e46daf273.png)
> 
> 
> ### 2. Label of the ratios issue.
> We miss recommended value and recommendation in P05F16 and P05F25
> 
> - The **Recommended value** should be "MEASURED"  
> 
> - The **Recommendation**  should be "Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the pumping process, such as  water flow and water consumption"
> 
> ## Ratio´s calculations
> Correctly implemented
> 

## Energy improvements identification

In this process the principal problem is in the simulation part, most of the improvements and recommendations are wrongly implemented, you must check it all.

When we set all the recommended values in EMSA efficiency questions, EMSA displays all the recommendations and issues.

## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
> 1. Missing question and working hours question issue

Done.

> 2. Label of the ratios issue.

Done.

**Comment by AaronITCL** [comment]
I make a mistake in this type of issues, the change is marked in bold, please check it again
### 2. Label of the ratios issue.
We miss recommended value and recommendation in P05F16 and P05F25

- The Recommended value **for both** should be "MEASURED"  

- **For P05F16** The Recommendation  should be **"Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the boiling process, such as energy consumption, water flow, production"**

- **For P05F25** The Recommendation should be "Consider installing measurement equipments  in all the main parameters that affect the energy efficiency from the **boiling** process, such as  water flow and water consumption"

**Comment by WINGSTeam** [comment]
Done.

**Comment by AaronITCL** [comment]
First comment updated

**Comment by WINGSTeam** [comment]
> Energy improvements identification
> In this process the principal problem is in the simulation part, most of the improvements and recommendations are wrongly implemented, you must check it all.
> 
> When we set all the recommended values in EMSA efficiency questions, EMSA displays all the recommendations and issues.

@AaronITCL The improvements work just fine for us. So, could you send us your user account (username, password) in order to check if there is any problem?
