### ISSUE TITLE
EMSA Lite improvements issue

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#66]
Checking the process improvements of some test scenario, we could find some of them which the improvements are not correctly set in the EMSA Lite.
### Boiling:
![image](https://user-images.githubusercontent.com/33861863/36975532-ac836310-207a-11e8-9ea2-5eeae79d59a4.png)

### Cooling:
![image](https://user-images.githubusercontent.com/33861863/36975550-b8e9e250-207a-11e8-9515-4ceb0c0423ed.png)

Maybe @CarbonTrust1 could help us here because as we can see in the D.4.1 Appendices Combined document, the cooling process is confusing, we cannot distinguish between the recommended values for cooling process from those dedicated to equipment.

**Comment by WINGSTeam** [comment]
We are not sure of what changes should be made, could you please elaborate on that? Do we have to wait for CarbonTrust to reply ?

**Comment by CarbonTrust1** [comment]
Hi all. David G and I have discussed this and ITCL and CT will make some changes to the WP 4.1 document and send this to WINGS to help improve the contents of the EMSA Lite recommendations.
