### ISSUE TITLE
Improvement and recommendation actions issue

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#67]
This issue refers to the improvement actions of the "Do you know" questions of many processes and equipments, currently almost all the direct improvement action of this type of question is "Install the necessary equipment to perform accurate measurements of the energy consumption" even if EMSA ask the water flow or the water consumption, so my proposal is to change that improvement message in function of the following conditions:

- if the question is "Do you know your energy consumption of the (equipment/process)?" improvement should be: **"Install the necessary equipment to perform accurate measurements of the energy consumption"**

- if the question is "Do you know the actual water flow of the process?" or "Do you know the real amount of used water?" (first appears in process questions and the second in equipments)  improvement should be: **"Install the necessary equipment to perform accurate measurements of the water flow"**

- if the question is "Does the process have water consumption?" improvement should be: **"Install the necessary equipment to perform accurate measurements of the water consumption"**

**Comment by WINGSTeam** [comment]
We will check that, because the changes that should be done will take a lot of time and is not easy to check all tables and all questions.

**Comment by WINGSTeam** [comment]
We updated the "Do you know" questions of all the processes and equipments with the improvements you proposed above. Also, if the question is "Does the process have water consumption?", we added the extra question "Do you know the water consumption", so that the user won't be asked the for the water consumption if it not exist.
