### ISSUE TITLE
7. Ballast and water cleaning water

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#68]
We will classify all the issues referenced to all the equipments and proccess validated by ITCL into 5 types, we will update this information in the future:

## Process question
Correctly implemented
## Ratios calculations
Correctly implemented
## Energy improvements identification

In this process the principal problem is in the simulation part, most of the improvements and recommendations are wrongly implemented, you must check it all.

When we set all the recommended values in EMSA efficiency questions, EMSA displays all the recommendations and issues.

## Saving simulation
In validation process
## Ratios display and comparison
In validation process

**Comment by WINGSTeam** [comment]
Improvements work fine now.
