### ISSUE TITLE
Improvement´s impact

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#7]
For the improvement´s impact display, there are 2 principal problems:

- Properly calculation of the efficiency ratios, saving values, investment for each improvement and recomendation selected according to the Socamex´s Excel for all equipments and process.

- The recommendations don´t have any saving or investment so, for now set a 0 value in all the cells for the recomenndations.

![image](https://user-images.githubusercontent.com/33861863/33311495-40d8e2c6-d425-11e7-9f3b-c937ff2faa14.png)

**Comment by WINGSTeam** [comment]
> The recommendations don´t have any saving or investment so, for now set a 0 value in all the cells for the recomenndations.

Could you please elaborate a bit more on that? Is there a document with information that we need to implement or we need to hide all the recommendations of this table ? 
Thanks!

**Comment by AaronITCL** [comment]
We need to separate the improvements from the recommendations, so for instance, you can separate the table, where the improvements keep the current columns and in the recommendations only appears the description.

**Comment by WINGSTeam** [comment]
Thanks Aaron for the clarification. However in the excels for each feature code we have the same savings and cost for recommendation and improvement. We didn't have separate. Shall we receive an update on this?

**Comment by AaronITCL** [comment]
Just, consider that the savings and investments affects only to the improvements and no to the recommendations, so when a user selects an improvement and simulates, it will appear in the table with the description, savings, investments, etc. But if he selects a recommendations and simulates will appear only the description.

**Comment by WINGSTeam** [comment]
> The recommendations don´t have any saving or investment so, for now set a 0 value in all the cells for the recommendations.

> Just, consider that the savings and investments affects only to the improvements and no to the recommendations, so when a user selects an improvement and simulates, it will appear in the table with the description, savings, investments, etc. But if he selects a recommendations and simulates will appear only the description.

Now only the description of the recommendation is shown.

**Comment by WINGSTeam** [comment]
> For the improvement´s impact display, there are 2 principal problems:
> 
> Properly calculation of the efficiency ratios, saving values, investment for each improvement and recomendation selected according to the Socamex´s Excel for all equipments and process.
> 
> The recommendations don´t have any saving or investment so, for now set a 0 value in all the cells for the recomenndations.

We have update the online tool and now everything is calculated as specified!
