### ISSUE TITLE
Corrections by Cork Institute of Technology

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#71]
You can find the Cork´s feedback attached below:
[Company test 1.docx](https://github.com/EnergyWater/EMSA/files/1788318/Company.test.1.docx)

**Comment by WINGSTeam** [comment]
[Company.test.1 - WINGS.docx](https://github.com/EnergyWater/EMSA/files/1796432/Company.test.1.-.WINGS.docx)
 You can find the changes we made and our comments, concerning the Cork´s feedback, attached above.
