### ISSUE TITLE
Energy Angels Information file

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#72]
I downloaded and tried to open the file with the information of a new EA from the administrator account, but the file is empty...(I opened it with excel but I have to say that it doesn't have an extension...the file is named "intoxls_php")
I'm not able to upload here the file because github says that that type of file is not supported.

**Comment by WINGSTeam** [comment]
Maybe you tried to export the 1st Angel with ID=0 , which is a testing Account for us and you cannot download any information for this account. I have disable the button for this account but for all the others it should be working without any problem. 
Thanks for noticing this!

**Comment by Matilde-SmartFuture** [comment]
Actually I exported the last EA in the list, ID=835, which is not a test account. 
However I tried with some other accounts and I noticed that this bug occurs only for the ones of which the second-to-last column "Status Date" is not compiled. Honestly I don't understand what that means!

**Comment by WINGSTeam** [comment]
The Status Date is for the date that an admin changes the status of an Angel/Company giving them rights to use the EMSA tool. In the past an admin had to accept anyone that registers to the EMSA, but now that we have change that and everyone is automatically accepted we have also change this mechanism and the button should export the information from any user not only the accepted by an Admin.

Could you also please recheck if is working for you? Thanks!

**Comment by Matilde-SmartFuture** [comment]
I rececked and now it's working fine. Thanks!
