### ISSUE TITLE
SOCAMEX review III (partial) 

### ISSUE THREAD

**Issue by SOCAMEX** [EnergyWater/EMSA#73]
Here we attach our updated review. The file is cumulative, in such a way that it also contains those issues which have been reviewed previously. The new content is allocated in the tab "SIMULATOR module". We continue working on the remaining processes and equipements. 
[Process-Equipment follow-up 16-MarSOCAMEX.xlsx](https://github.com/EnergyWater/EMSA/files/1824295/Process-Equipment.follow-up.16-MarSOCAMEX.xlsx)

**Comment by WINGSTeam** [comment]
The problems listed in the file are now fixed, but we have a question. Since the production is measured in production units, shouldn't the Production Ratios be measured in (m3/production)?

**Comment by SOCAMEX** [comment]
Yes, the production ratios would be correctly measured in m3/production.

**Comment by WINGSTeam** [comment]
> Yes, the production ratios would be correctly measured in m3/production.

Updated.
