### ISSUE TITLE
P34 Cooling of pressure equipment_scenario+results_SMART FUTURE

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#75]
[P34 Cooling of pressure equipment_scenario+results_SMART FUTURE.xlsx](https://github.com/EnergyWater/EMSA/files/1829801/P34.Cooling.of.pressure.equipment_scenario.results_SMART.FUTURE.xlsx)

**Comment by WINGSTeam** [comment]
We reviewed your file and the problems are fixed now. Regarding to the results module, it only exists for testing purposes. It’s for helping the user to revisit the values he has completed and it has nothing to do with the functionality of the tool and in the final version it probably will be hidden. So, we don’t think it’s necessary to hide particular answers, as long as these fields have no values. Also, as regards to the questions about the working hours, the user has to complete them with hour units only, so we the tool can calculate if the value is over 366*24=8784.
