### ISSUE TITLE
P29-30-31-32-33-34_Simulator_Energy improvements

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#77]
[P29-30-31-32-33-34_Simulator_Energy improvements_SMART FUTURE.xlsx](https://github.com/EnergyWater/EMSA/files/1847547/P29-30-31-32-33-34_Simulator_Energy.improvements_SMART.FUTURE.xlsx)

**Comment by WINGSTeam** [comment]
The recommendations about the energy and water consumption have added as you suggest. Regarding to P34 (Cooling of pressure equipment), you need to be more specific, about the P34F05. What should be the improvement? And about P32, are you facing any problem accessing that particular process?

**Comment by Matilde-SmartFuture** [comment]
Regarding P34F05, I don't understand myself what are the suggested intervention, so I can't be more specific about the improvement to do. Maybe ITCL or SOCAMEX could help.
About P32, as I stated in the review of scenario module, I don't understand what this process consists of, which literally means "control of any losses". If it is intended as doing a check process (about what?), it seems that none of the questions is relevant ...In WP1 this process was included in METALLURGICAL INDUSTRY - FOUNDRIES - WATER PROCESS TREATMENT, anyone could help?
