### ISSUE TITLE
Design or Grammar Issue

### ISSUE THREAD

**Issue by MPetrakkas** [EnergyWater/EMSA#80]
P45F27 - Does your system **use a** use a web scrubber? - The word use a is used twice (this is also wrong on the excel)
P43F20 - Do you know water consumption - should be <Do you know **the** water consumption>
E39F27 - Do you **regulare** cleaning time with the water temperature? - change with **regulate**
E29F15 - Is process water disinfected? - Is **the** process water disinfected
E39F04 - Which is the motorss nominal power ? - should be <**What** is the **motors's** nominal power>
Also I am not too sure if the E39F04 question is very clear as it doesn't clearly state if we talk about the total power of for one unit

**Comment by WINGSTeam** [comment]
> E29F15 - Is process water disinfected? - Is the process water disinfected

This is not the "E29F15"  question.

> Also I am not too sure if the E39F04 question is very clear as it doesn't clearly state if we talk about the total power of for one unit

Maybe @david-ITCL or @AaronITCL could answer that.

All the other issues are fixed.
