### ISSUE TITLE
Management Questions

### ISSUE THREAD

**Issue by MPetrakkas** [EnergyWater/EMSA#82]
1. I believe there should be a submit button on the management questions just to avoid confusion.

2. The results section of the Management questions seems to provide postitive (1point) value to negative actions and we will need to reconsider this!

**Comment by WINGSTeam** [comment]
> I believe there should be a submit button on the management questions just to avoid confusion.

The submit button in this page will not have any functionality, since the management questions are already submitted from the previous page.


> The results section of the Management questions seems to provide postitive (1point) value to negative actions and we will need to reconsider this

This scoring process is built based on the specifications we were given.
