### ISSUE TITLE
Unmarked Tables - Savings Simulator

### ISSUE THREAD

**Issue by MPetrakkas** [EnergyWater/EMSA#83]
There needs to be a genereal reassesment of the tables being generated so that the x and y axis are clearly labelled

**Comment by WINGSTeam** [comment]
> There needs to be a genereal reassesment of the tables being generated so that the x and y axis are clearly labelled

These charts are automatically provided and they have a standard form. So we cannot add extra information on them.  If you think that they are not understandable, you can provide us with some small text explaining how the charts work and we will add it near the chart for more clearance.
