### ISSUE TITLE
EMSA pro validation

### ISSUE THREAD

**Issue by cbarbaux** [EnergyWater/EMSA#84]
Hello everyone

In the attached file you will find the comments from GreenFlex as for the validation of the EMSA pro.
There are several comments to make the data evaluation part more understandable and then many inputs regarding tables and graphs that don't appear or of which values seem wrong.

Hope this helps,

[EMSA pro validation - GF input.xlsx](https://github.com/EnergyWater/EMSA/files/1946276/EMSA.pro.validation.-.GF.input.xlsx)

**Comment by WINGSTeam** [comment]
We reviewed your validation file. Thank you for your feedback. We attach below, a doc file with our comments, and an excel file with the mapping of  the processes and equipment and their charts.
[EmsaProValidationWings.docx](https://github.com/EnergyWater/EMSA/files/1951125/EmsaProValidationWings.docx)
[_0_Indicators.Summary.Table.v3 (1).xlsx](https://github.com/EnergyWater/EMSA/files/1951127/_0_Indicators.Summary.Table.v3.1.xlsx)

**Comment by cbarbaux** [comment]
@WINGSTeam Thanks for the feedback.
We've been trying to check the display problem that we have with all values in charts appearing at 0. And so far we don't understand where it is coming from. A simple example: in the efficiency questions, regarding boiler, the tool asked for the boiler efficiency. We put 91% but in the results it appears at 0.
Do you have something similar on your side?
