### ISSUE TITLE
Heating process and Heaters issue

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#85]
There is a problem with the functionality of the EMSA when a Heating process with 2 heaters configuration is set as it is in the following picture.

![image](https://user-images.githubusercontent.com/33861863/39510336-b3f6e580-4de9-11e8-8c0e-138239033e35.png)

After a user sets some values in the two heaters, the first one modificated takes the values of the second one.

**Comment by WINGSTeam** [comment]
Problem fixed!
