### ISSUE TITLE
Grammatical corrections for EMSA equipment

### ISSUE THREAD

**Issue by CTC-CIT** [EnergyWater/EMSA#89]
We have reviewed and revised the equipment used in the processes we were assigned in the attached excel file.  Examples include replacing 'which' with 'what', correcting syntax errors and changing hp to kW.  The original is also attached for comparison purposes (original file CTC equipment.xlsx)
[Original file CTC equipment d001.xlsx](https://github.com/EnergyWater/EMSA/files/2008628/Original.file.CTC.equipment.d001.xlsx)
.
[CTC-CIT equipment d001.xlsx](https://github.com/EnergyWater/EMSA/files/2008607/CTC-CIT.equipment.d001.xlsx)

**Comment by WINGSTeam** [comment]
The corrections you proposed are done for all the equipment except Chiller. We are a bit confused about chiller. We cannot really understand what "tonnes" means, and it appears in a lot of your corrected questions (e.g. tonnes is your type of Chiller?). Could you check it once again please and let us know, or give us an updated version if its a mistake?

**Comment by CTC-CIT** [comment]
Thanks for spotting that! When replacing 'Which' with 'What' it was replaced with tonnes in error (this was previously used to replace tons (US unit) with tonnes (SI unit)).  Corrected file attached.
[CTC-CIT equipment d002.xlsx](https://github.com/EnergyWater/EMSA/files/2009166/CTC-CIT.equipment.d002.xlsx)

**Comment by WINGSTeam** [comment]
Ok, thanks for the update. The corrections for the chiller are done as well.
