### ISSUE TITLE
Grammar issues

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#9]
This issue regards all the grammar issues that the partners consider necessary to solve in this module.

_Please, comment the new feedback indicating the origin of the issue in orden from the scenarios module screen to the particular issue starting with "Feedback:", to difference this comments from others, for example, Efficiency Questions - Equipment Pump - E01F24 and then the issue_

**Comment by AaronITCL** [comment]
In this comment, i will summary all the feedback received related to this module and this issue.
Also, i will indicate which ones are proposals. 
Finally, take into account that all of them are non-priority, the ones considered important will appear in another issue.
## GreenFlex
1. There are several minor English mistakes in the Management questions for the moment.

**Comment by AaronITCL** [comment]
Feedback:
Efficiency Questions - Eqipment Blower - E26F10 -> Orthographic issues.

![image](https://user-images.githubusercontent.com/33861863/33363284-1283d1f4-d4e0-11e7-9995-1d5fd018cfda.png)

Change that feature name by; "Which is the motor´s nominal power?"

**Comment by WINGSTeam** [comment]
> Feedback:
> Efficiency Questions - Eqipment Blower - E26F10 -> Orthographic issues.
> 
> 
> 
> Change that feature name by; "Which is the motor´s nominal power?"

Done

**Comment by WINGSTeam** [comment]
> GreenFlex
> 
> There are several minor English mistakes in the Management questions for the moment.

Could you please clarify which are the questions and the mistakes you mention in order to correct them?
