### ISSUE TITLE
CT EMSA pro validation round 2 excel file

### ISSUE THREAD

**Issue by CarbonTrust1** [EnergyWater/EMSA#92]
Please find attached EMSA pro validation feedback from CT previously issued to ITCL
[Process-Equipment follow-up 26-Apr CT (CT Comment).xlsx](https://github.com/EnergyWater/EMSA/files/2022085/Process-Equipment.follow-up.26-Apr.CT.CT.Comment.xlsx)

**Comment by WINGSTeam** [comment]
We reviewed your file and made some comments. First, as we mention in our response file, all things related to the content of the procedures are not our responsibility, so we will refer you to issue #96 for this kind of comments (like the meaning of the questions or the recommendations, explaining the graphs results etc.).  All the issues you mention, that related to the functionality of the tool are reviewed and fixed. If you have any comment, please let us know.
You can find the files attached below. Thank you.
[Process-Equipment.follow-up.26-Apr.CT.CT.Comment -WingsResponse.xlsx](https://github.com/EnergyWater/EMSA/files/2031609/Process-Equipment.follow-up.26-Apr.CT.CT.Comment.-WingsResponse.xlsx)
[_0_Indicators.Summary.Table.v3.xlsx](https://github.com/EnergyWater/EMSA/files/2031610/_0_Indicators.Summary.Table.v3.xlsx)
[EMSA SIMULATOR MODULE DECIMALS v2.docx](https://github.com/EnergyWater/EMSA/files/2031611/EMSA.SIMULATOR.MODULE.DECIMALS.v2.docx)

**Comment by CarbonTrust1** [comment]
[Process-Equipment.follow-up.26-Apr.CT.CT.Comment.-WingsResponse - CT final check.xlsx](https://github.com/EnergyWater/EMSA/files/2053559/Process-Equipment.follow-up.26-Apr.CT.CT.Comment.-WingsResponse.-.CT.final.check.xlsx)
We have gone through the EMSA and checked our assigned processes and equipment. Most things appear to have been addressed, but from what we can see the financial saving calculations are still not calculating the correct figures in the Documented Savings table. Can you please check these.
We acknowledge that many of our comments relate to more aesthetic and usability issues that may need to be addressed with Socamex and ITCL at a later date and will not be addressed through this cycle of validation. 
If you have any questions please let me know.

**Comment by WINGSTeam** [comment]
> we can see the financial saving calculations are still not calculating the correct figures in the Documented Savings table. Can you please check these.

You are totally right, thanks for that. Cost saving calculation is now fixed. Please, check it as well.

Regarding equipment sieve, efficiency ratio nominal value is correct. It's E17F04/E17F03 = 10/100 = 0.1.
Efficiency ratio optimum does not exist for this equipment. You can check it in the indicator file.
