### ISSUE TITLE
Error simulating improvement

### ISSUE THREAD

**Issue by Matilde-SmartFuture** [EnergyWater/EMSA#93]
Trying to simulate the improvement action for the blower I get this error message
![immagine](https://user-images.githubusercontent.com/33963050/40304589-9ce6c226-5cf7-11e8-9f4e-3bd05cdfb102.png)
I think it may be due to the presence of the apostrofhe in the sentence.

**Comment by WINGSTeam** [comment]
It's fixed now. Thank you for noticing it.
