### ISSUE TITLE
Copy scenario issue

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#94]
The "Copy scenario" functionality in EMSA has some issues:
Firstly when a user copies an scenario EMSA displays the following message.
![image](https://user-images.githubusercontent.com/33861863/40306709-fe86fa16-5cff-11e8-8939-97dc3d700ee8.png)
However, clicking in "Home Page" I can return to the EMSA home page and see the copy scenario on the Data evaluation module.
This copy function seems inclomplete, some data as it is the general questions or the process and equipmentes are copied correctly but not the data from those equipmentes and processes as you can see in the picture.

**Data from the original scenario**
![image](https://user-images.githubusercontent.com/33861863/40306812-5f58def4-5d00-11e8-8c02-91b8e317d554.png)

**Data from the copied scenario (same process)**
![image](https://user-images.githubusercontent.com/33861863/40306808-5c284e9a-5d00-11e8-90fd-50ecf608b246.png)

As you can see the sheet is empty.

**Comment by WINGSTeam** [comment]
> Firstly when a user copies an scenario EMSA displays the following message.

This issue is fixed.

> However, clicking in "Home Page" I can return to the EMSA home page and see the copy scenario on the Data evaluation module.
> This copy function seems inclomplete, some data as it is the general questions or the process and equipmentes are copied correctly but not the data from those equipmentes and processes as you can see in the picture.

You are right about that too, we will check it as soon as possible.

**Comment by WINGSTeam** [comment]
> However, clicking in "Home Page" I can return to the EMSA home page and see the copy scenario on the Data evaluation module.
> This copy function seems inclomplete, some data as it is the general questions or the process and equipmentes are copied correctly but not the data from those equipmentes and processes as you can see in the picture.

Copy Scenario problem fixed, thanks for mentioned it.
