### ISSUE TITLE
Saving simulator Errror?

### ISSUE THREAD

**Issue by MPetrakkas** [EnergyWater/EMSA#95]
In the Savings Simulatora, under the Equipment, when choosing the efficiency measure of the equipment, the ranking gets an -ve %ge value. This happens in both **Dewaterting section and Handling System**. 

![dewatering sect - negative ranking](https://user-images.githubusercontent.com/37288518/40357727-c416991a-5dc5-11e8-8981-3d5d574d0688.jpg)

**Comment by WINGSTeam** [comment]
That is not an error, it could happen. If your account is old, by the time you implement your improvements, its possible other companies with better performance have been registered in the tool, so their go higher in the ranking.
