### ISSUE TITLE
Wings directions about evaluation process

### ISSUE THREAD

**Issue by WINGSTeam** [EnergyWater/EMSA#96]
Μany of the comments we have recently received from the evaluation process, are related to the content of the questions and the improvement proposals. As you all know, the questions are provided to us by SOCAMEX and ITCL and we are not responsible about their meaning. So, we need the approval from all the partners especially those two, in order to make this kind of changes. 
Also, some of your comments are mention that some questions are not clear enough, or that the user needs extra guidance to understand the meaning of certain procedures. Most of these comments are true and we agree that some fields need more explanation, but these directions need to provided to us. 
All the content that’s implemented on the tool at this time is based on the specifications. So, when you think that some text is not clear enough, please provide us with the suitable one, after consulting SOCAMEX or ITCL.
Also, most of the questions are repeated in the majority of processes and equipment, so some changes need to be universal. We think it would be better to be consistent with the wording of the questions, especially the most repeated ones.
So, we propose to SOCAMEX and ICTL to review all the open github issues and answer or provide us guidance, with all the question related comments and issues. 
Of course, all the other comments about errors, bugs or the functionality of the tool are for us to review and fix.
 
Thank you all, 
Wings Team

@AaronITCL @david-ITCL @SoniaOIEau @DavidFraile @CTC-CIT @CarbonTrust1 @cbarbaux @maite112 @Matilde-SmartFuture @MPetrakkas

**Comment by Matilde-SmartFuture** [comment]
Hi all
as mentioned in my latest email, I prepared a file with some proposals of improvement to add into the tool. I attach the file here so all partners could have a look in order to reach a full agreement.
I also would like to remind that there’s a still pending validation process: P32 – Leakage checks, as I already commented on GitHub.
We don't understand what this process consists of. 
It literally means "control of any losses": if it is intended as "doing a check process" (what check? which parameters?), it seems that none of the questions is relevant... 
In WP1 this process was included in METALLURGICAL INDUSTRY - FOUNDRIES - WATER PROCESS TREATMENT: as we don’t have expertise on that industrial sector, we do need help to validate it.
Thanks,
Matilde

@WINGSTeam @david-ITCL @AaronITCL @SoniaOIEau @DavidFraile @CTC-CIT @CarbonTrust1 @maite112 @MPetrakkas 

[Proposal for EMSA improvement to be agreed_SF.xlsx](https://github.com/EnergyWater/EMSA/files/2029931/Proposal.for.EMSA.improvement.to.be.agreed_SF.xlsx)

**Comment by AaronITCL** [comment]
Dear @Matilde-SmartFuture 

It is not needed  to understand completely all the processes and the equipments for the validation process, the aim of the validation is to check if the EMSA is working in relation to the "excels" done by SOCAMEX relative to your process and equipments, so you only have to check the functionalities that appears in the document "Process-Equipment.follow-up".
Those functionalities are:

- Process questions, check if the EMSA is displaying correctly all the questions presented in the SOCAMEX’s excels.

- Ratio´s calculations, check with the data introduced if EMSA is correctly calculating the ratios.

- Energy improvements identification, check with the data introduced if EMSA is displaying correctly the improvements and recommendations in the Simulator module.

- Saving simulation, check if the status after the improvement actions is correctly calculated based on the savings and the estimated cost for the improvements simulated, and if this savings and estimated cost are correctly identify to the improvement simulated based on the "excels" documents.

- Ratios display and comparison check if the data that appears in the benchmarking is referred to the data inserted.

On the other hand, if you want to know the technical aspects or how that process and equipments works you must ask directly to @SOCAMEX

**Comment by AaronITCL** [comment]
Dear all,

the priority now to make the EMSA 100% workable, is to solve all the functionality, display, calculations  or grammar issues of the tool.
EMSA must be based 100% on SOCAMEX Excels as them are now, excepting the grammar issues which must be updated on the Excels too, this means that to validate those process and equipments assigned to each partner you only have to check that all the features of those documents are correctly implemented on the EMSA.
Repeating the message written to Matilde, the aim of the validation is to check if the EMSA is working in relation to the "excels" done by SOCAMEX relative to your process and equipments checking the following functionalities:

- Process questions, check if the EMSA is displaying correctly all the questions presented in the SOCAMEX’s excels.

- Ratio´s calculations, check with the data introduced if EMSA is correctly calculating the ratios.

- Energy improvements identification, check with the data introduced if EMSA is displaying correctly the improvements and recommendations in the Simulator module.

- Saving simulation, check if the status after the improvement actions is correctly calculated based on the savings and the estimated cost for the improvements simulated, and if this savings and estimated cost are correctly identify to the improvement simulated based on the "excels" documents.

- Ratios display and comparison check if the data that appears in the benchmarking is referred to the data inserted.

Any change relative to those SOCAMEX documents are not a priority now, those issues are for example:

- Guidance

- Technical data (e.g. changing a recommended value or an equation) 

- Content of the questions, improvements and recommendations (e.g. change or add a question, improvement or recommendation)

- Adding new questions, process, equipments, etc... 

As a summary, we need to focus on the task of making the EMSA 100% workable relative to the SOCAMEX’s  EXCEL documents .

@WINGSTeam @SoniaOIEau  @david-ITCL @DavidFraile @CTC-CIT @CarbonTrust1 @maite112 @MPetrakkas  @Matilde-SmartFuture  @cbarbaux @SOCAMEX

**Comment by Matilde-SmartFuture** [comment]
I just submitted a new issue for the process P32 Leakage checks, that we evaluated according to Aaron's directives.
I also closed the issue #77 because the only pending item was that process.
